// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

#using_animtree("generic_human");

main()
{
    scripts\code\character::setmodelfromarray( xmodelalias\bodies_al_qatala_urban_lmg_variant::main() );
    scripts\code\character::attachhead( "heads_al_qatala_urban_ar_variant", xmodelalias\heads_al_qatala_urban_ar_variant::main() );
    self.bhasthighholster = 0;
    self.animtree = "generic_human";
    self.animationarchetype = "rebel";
    self.voice = "alqatala";
    self setclothtype( "vestlight" );

    if ( issentient( self ) )
        self sethitlocdamagetable( "ai_lochit_dmgtable" );

    self useanimtree( #animtree );
}

precache()
{
    scripts\code\character::precachemodelarray( xmodelalias\bodies_al_qatala_urban_lmg_variant::main() );
    scripts\code\character::precachemodelarray( xmodelalias\heads_al_qatala_urban_ar_variant::main() );
}

main_mp()
{
    self.animationarchetype = "rebel";
    self.voice = "alqatala";
    scripts\code\character::setmodelfromarray( xmodelalias\bodies_al_qatala_urban_lmg_variant::main() );
    scripts\code\character::attachhead( "heads_al_qatala_urban_ar_variant", xmodelalias\heads_al_qatala_urban_ar_variant::main() );
}

precache_mp( var_0 )
{
    level.agent_definition[var_0]["animclass"] = "rebel";
}
