// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

#using_animtree("generic_human");

main()
{
    self setmodel( "body_russian_army_ar_5" );
    scripts\code\character::attachhead( "russian_army_heads_gasmask", xmodelalias\russian_army_heads_gasmask::main() );
    scripts\code\character::attachhat( "russian_army_ar_5_hats_gasmask", xmodelalias\russian_army_ar_5_hats_gasmask::main() );
    self.bhasthighholster = 0;
    self.animtree = "generic_human";
    self.animationarchetype = "soldier";
    self.voice = "russian";
    self setclothtype( "vestlight" );

    if ( issentient( self ) )
        self sethitlocdamagetable( "ai_lochit_dmgtable" );

    self useanimtree( #animtree );
}

precache()
{
    precachemodel( "body_russian_army_ar_5" );
    scripts\code\character::precachemodelarray( xmodelalias\russian_army_heads_gasmask::main() );
    scripts\code\character::precachemodelarray( xmodelalias\russian_army_ar_5_hats_gasmask::main() );
}

main_mp()
{
    self.animationarchetype = "soldier";
    self.voice = "russian";
    self setmodel( "body_russian_army_ar_5" );
    scripts\code\character::attachhead( "russian_army_heads_gasmask", xmodelalias\russian_army_heads_gasmask::main() );
    scripts\code\character::attachhat( "russian_army_ar_5_hats_gasmask", xmodelalias\russian_army_ar_5_hats_gasmask::main() );
}

precache_mp( var_0 )
{
    level.agent_definition[var_0]["animclass"] = "soldier";
}
