// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

#using_animtree("generic_human");

main()
{
    self setmodel( "civ_doctor_male_body" );
    scripts\code\character::attachhead( "civilian_syrkistan_male_head", xmodelalias\civilian_syrkistan_male_head::main() );
    self.bhasthighholster = 0;
    self.animtree = "generic_human";
    self.animationarchetype = "civilian";
    self.voice = "alqatala";
    self setclothtype( "vestlight" );

    if ( issentient( self ) )
        self sethitlocdamagetable( "ai_lochit_dmgtable" );

    self useanimtree( #animtree );
}

precache()
{
    precachemodel( "civ_doctor_male_body" );
    scripts\code\character::precachemodelarray( xmodelalias\civilian_syrkistan_male_head::main() );
}

main_mp()
{
    self.animationarchetype = "civilian";
    self.voice = "alqatala";
    self setmodel( "civ_doctor_male_body" );
    scripts\code\character::attachhead( "civilian_syrkistan_male_head", xmodelalias\civilian_syrkistan_male_head::main() );
}

precache_mp( var_0 )
{
    level.agent_definition[var_0]["animclass"] = "civilian";
}
