NAME scripts\cp\vehicles\damage_cp.gsc
VERSION 0
CHECKSUM 0xca12c5bd
######################################################
####################  DEV BLOCKS  ####################
######################################################
# damage_cp::init_damage_callback_data@a
DEVBLOCK 0xa94
# damage_cp::get_pre_mod_damage_callback@a
DEVBLOCK 0xb34
# damage_cp::get_pre_mod_damage_callback@22
DEVBLOCK 0xb4c
# damage_cp::get_post_mod_damage_callback@a
DEVBLOCK 0xba1
# damage_cp::get_post_mod_damage_callback@22
DEVBLOCK 0xbb9
# damage_cp::get_death_callback@a
DEVBLOCK 0xc0e
# damage_cp::get_death_callback@22
DEVBLOCK 0xc26
# damage_cp::set_pre_mod_damage_callback@12
DEVBLOCK 0xc83
# damage_cp::set_pre_mod_damage_callback@2a
DEVBLOCK 0xc9b
# damage_cp::set_post_mod_damage_callback@12
DEVBLOCK 0xcf9
# damage_cp::set_post_mod_damage_callback@2a
DEVBLOCK 0xd11
# damage_cp::set_death_callback@12
DEVBLOCK 0xd6f
# damage_cp::set_death_callback@2a
DEVBLOCK 0xd87
# damage_cp::callback_vehicledeath@62
DEVBLOCK 0x1c9f
# damage_cp::init_mod_damage_data@a
DEVBLOCK 0x1ce9
# damage_cp::get_mod_damage_modifier@b3
DEVBLOCK 0x1e50
# damage_cp::get_mod_damage_modifier@c9
DEVBLOCK 0x1e66
# damage_cp::get_vehicle_mod_damage_data@1b
DEVBLOCK 0x209d
# damage_cp::get_weapon_class_mod_damage_data@1b
DEVBLOCK 0x2161
# damage_cp::get_perk_mod_damage_data@1b
DEVBLOCK 0x21ff
# damage_cp::get_attachment_mod_damage_data@1b
DEVBLOCK 0x229d
# damage_cp::set_weapon_class_mod_damage_data@27
DEVBLOCK 0x2347
# damage_cp::set_weapon_class_mod_damage_data_for_vehicle@38
DEVBLOCK 0x23be
# damage_cp::set_perk_mod_damage_data@27
DEVBLOCK 0x2459
# damage_cp::set_perk_mod_damage_data_for_vehicle@38
DEVBLOCK 0x24d0
# damage_cp::set_attachment_mod_damage_data@27
DEVBLOCK 0x256b
# damage_cp::set_attachment_mod_damage_data_for_vehicle@38
DEVBLOCK 0x25e2
# damage_cp::init_hit_damage_data@a
DEVBLOCK 0x2696
# damage_cp::get_vehicle_hit_damage_data@1b
DEVBLOCK 0x2823
# damage_cp::get_weapon_hit_damage_data@1b
DEVBLOCK 0x28e7
# damage_cp::set_vehicle_hit_damage_data@1b
DEVBLOCK 0x29ab
# damage_cp::set_vehicle_hit_damage_data_for_weapon@2c
DEVBLOCK 0x2a09
# damage_cp::set_weapon_hit_damage_data@1b
DEVBLOCK 0x2a63
# damage_cp::set_weapon_hit_damage_data_for_vehicle@2c
DEVBLOCK 0x2ac1
# damage_cp::function_d508766fa2962e37@a
DEVBLOCK 0x2b0a
# damage_cp::init_emp_damage_data@a
DEVBLOCK 0x2c99
# damage_cp::get_emp_damage_callback@17
DEVBLOCK 0x2d69
# damage_cp::get_emp_damage_callback@41
DEVBLOCK 0x2d93
# damage_cp::set_emp_damage_callback@1f
DEVBLOCK 0x2deb
# damage_cp::set_emp_damage_callback@49
DEVBLOCK 0x2e15
