const char* poolNames[] {
    "physicslibrary", // 0
    "physicssfxeventasset", // 1
    "physicsvfxeventasset", // 2
    "physicsasset", // 3
    "physicsfxpipeline", // 4
    "physicsfxshape", // 5
    "physicsdebugdata", // 6
    "xanim", // 7
    "xmodelsurfs", // 8
    "xmodel", // 9
    "mayhem", // a
    "material", // b
    "computeshader", // c
    "libshader", // d
    "vertexshader", // e
    "hullshader", // f
    "domainshader", // 10
    "pixelshader", // 11
    "techset", // 12
    "image", // 13
    "soundglobals", // 14
    "soundmodeglobals", // 15
    "soundbank", // 16
    "soundbanktransient", // 17
    "col_map", // 18
    "com_map", // 19
    "glass_map", // 1a
    "aipaths", // 1b
    "navmesh", // 1c
    "tacgraph", // 1d
    "airegiongraphs", // 1e
    "map_ents", // 1f
    "fx_map", // 20
    "gfx_map", // 21
    "gfx_map_trzone", // 22
    "iesprofile", // 23
    "lightdef", // 24
    "gradingclut", // 25
    "ui_map", // 26
    "fogspline", // 27
    "animclass", // 28
    "playeranim", // 29
    "gesture", // 2a
    "localize", // 2b
    "attachment", // 2c
    "weapon", // 2d
    "vfx", // 2e
    "impactfx", // 2f
    "surfacefx", // 30
    "aitype", // 31
    "mptype", // 32
    "character", // 33
    "xmodelalias", // 34
    "rawfile", // 35
    "scriptfile", // 36
    "scriptdebugdata", // 37
    "stringtable", // 38
    "leaderboarddef", // 39
    "virtualleaderboarddef", // 3a
    "ddl", // 3b
    "tracer", // 3c
    "vehicle", // 3d
    "addon_map_ents", // 3e
    "netconststrings", // 3f
    "luafile", // 40
    "scriptable", // 41
    "equipsndtable", // 42
    "vectorfield", // 43
    "particlesimanimation", // 44
    "streaminginfo", // 45
    "laser", // 46
    "gameprops", // 47
    "materialstandard", // 48
    "beam", // 49
    "ttf", // 4a
    "suit", // 4b
    "suitanimpackage", // 4c
    "camera", // 4d
    "hudoutline", // 4e
    "rumble", // 4f
    "rumblegraph", // 50
    "animpkg", // 51
    "sfxpkg", // 52
    "vfxpkg", // 53
    "footstepvfx", // 54
    "behaviortree", // 55
    "behaviorsequencer", // 56
    "sightconfig", // 57
    "aianimset", // 58
    "aiasm", // 59
    "proceduralbones", // 5a
    "dynamicbones", // 5b
    "reticle", // 5c
    "xanimcurve", // 5d
    "coverselector", // 5e
    "enemyselector", // 5f
    "clientcharacter", // 60
    "clothasset", // 61
    "cinematicmotion", // 62
    "accessory", // 63
    "locdmgtable", // 64
    "bulletpenetration", // 65
    "scriptbundle", // 66
    "blendspace2d", // 67
    "xcam", // 68
    "camo", // 69
    "xcompositemodel", // 6a
    "xmodeldetailcollision", // 6b
    "streamkey", // 6c
    "streamtreeoverride", // 6d
    "keyvaluepairs", // 6e
    "stterrain", // 6f
    "nativescriptpatch", // 70
    "collisiontile", // 71
    "execution", // 72
    "carryobject", // 73
    "soundbanklist", // 74
    "weaponaccuracy", // 75
    "decalvolumematerial", // 76
    "decalvolumemask", // 77
    "dynentitylist", // 78
    "fx_map_trzone", // 79
    "volumetricheightmap", // 7a
    "dlogschema", // 7b
    "edgelist", // 7c
    "xboneset", // 7d
    "ragdollasset", // 7e
    "physicsbonegraph", // 7f
    "curve", // 80
    "skeletonconstraints", // 81
    "triggereffect", // 82
    "weapontrigger", // 83
    "volumetriccloud", // 84
    "codcasterdata", // 85
    "watersystem", // 86
    "waterbuoyancy", // 87
    "keybinds", // 88
    "calloutmarkerping", // 89
    "lightstate", // 8a
    "radianttelemetry", // 8b
    "aimarkup", // 8c
    "scenario", // 8d
    "leagueplayseasons", // 8e
    "reactivestageset", // 8f
};