// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    setdvar( "_encstr_84D20BC8A9B7B51394314358D9", 0.2 );
    setdvar( "_encstr_9A400AEB2390F1FD098F0AC5", 0 );
    setdvar( "_encstr_994D0BE8B1B5B26797B05B5AD6", 2 );
    setdvar( "_encstr_B4F00B9C51C42D9CC43982265A", 1 );
    setdvar( "_encstr_846619C2B76BE35FC67FE9F90BD89B0797F07225731F6381C9E8DF", 1 );
    setdvar( "_encstr_A5AD0AB9C789FB64295D839C", 1 );
    setdvar( "_encstr_BE360B89A215A69A0AD229B47A", 8 );
}
