NAME scripts\core_common\ai\archetype_civilian.gsc
VERSION 0
CHECKSUM 0x73ff449c
######################################################
####################  DEV BLOCKS  ####################
######################################################
# archetypecivilian::registerbehaviorscriptfunctions@62
DEVBLOCK 0x4ca
# archetypecivilian::registerbehaviorscriptfunctions@b2
DEVBLOCK 0x51a
# archetypecivilian::registerbehaviorscriptfunctions@ea
DEVBLOCK 0x552
# archetypecivilian::registerbehaviorscriptfunctions@172
DEVBLOCK 0x5da
# archetypecivilian::registerbehaviorscriptfunctions@1da
DEVBLOCK 0x642
# archetypecivilian::registerbehaviorscriptfunctions@242
DEVBLOCK 0x6aa
# archetypecivilian::registerbehaviorscriptfunctions@2aa
DEVBLOCK 0x712
# archetypecivilian::registerbehaviorscriptfunctions@312
DEVBLOCK 0x77a
# archetypecivilian::registerbehaviorscriptfunctions@372
DEVBLOCK 0x7da
# archetypecivilian::registerbehaviorscriptfunctions@3d2
DEVBLOCK 0x83a
# archetypecivilian::registerbehaviorscriptfunctions@432
DEVBLOCK 0x89a
# archetypecivilian::registerbehaviorscriptfunctions@492
DEVBLOCK 0x8fa
# archetypecivilian::registerbehaviorscriptfunctions@4f2
DEVBLOCK 0x95a
# archetypecivilian::registerbehaviorscriptfunctions@552
DEVBLOCK 0x9ba
# archetypecivilian::registerbehaviorscriptfunctions@5b2
DEVBLOCK 0xa1a
# archetypecivilian::registerbehaviorscriptfunctions@612
DEVBLOCK 0xa7a
# archetypecivilian::registerbehaviorscriptfunctions@672
DEVBLOCK 0xada
# archetypecivilian::registerbehaviorscriptfunctions@6da
DEVBLOCK 0xb42
# archetypecivilian::registerbehaviorscriptfunctions@742
DEVBLOCK 0xbaa
# archetypecivilian::function_49d80e54@22
DEVBLOCK 0xc9a
# archetypecivilian::rioterchoosepositionservice@1ee
DEVBLOCK 0x10de
# archetypecivilian::civilianwanderservice@206
DEVBLOCK 0x163e
