NAME scripts\core_common\ai\archetype_damage_utility.gsc
VERSION 0
CHECKSUM 0xcc75433c
######################################################
####################  DEV BLOCKS  ####################
######################################################
# aiutility::registerbehaviorscriptfunctions@2
DEVBLOCK 0x3c2
# aiutility::registerbehaviorscriptfunctions@6a
DEVBLOCK 0x42a
# aiutility::registerbehaviorscriptfunctions@d2
DEVBLOCK 0x492
# aiutility::registerbehaviorscriptfunctions@13a
DEVBLOCK 0x4fa
# aiutility::registerbehaviorscriptfunctions@1a2
DEVBLOCK 0x562
# aiutility::registerbehaviorscriptfunctions@20a
DEVBLOCK 0x5ca
# aiutility::registerbehaviorscriptfunctions@272
DEVBLOCK 0x632
# aiutility::registerbehaviorscriptfunctions@2da
DEVBLOCK 0x69a
# aiutility::registerbehaviorscriptfunctions@342
DEVBLOCK 0x702
# aiutility::registerbehaviorscriptfunctions@3aa
DEVBLOCK 0x76a
# aiutility::registerbehaviorscriptfunctions@412
DEVBLOCK 0x7d2
# aiutility::registerbehaviorscriptfunctions@47a
DEVBLOCK 0x83a
# aiutility::bb_getdamagedirection@2
DEVBLOCK 0xf0a
# aiutility::bb_actorgetdamagelocation@1a
DEVBLOCK 0x1042
# aiutility::bb_actorgetdamagelocation@344
DEVBLOCK 0x136c
# aiutility::bb_getdamagetaken@22
DEVBLOCK 0x1722
# aiutility::bb_actorgetfataldamagelocation@12
DEVBLOCK 0x18ba
# aiutility::addaioverridedamagecallback@4a
DEVBLOCK 0x1b42
# aiutility::addaioverridedamagecallback@72
DEVBLOCK 0x1b6a
# aiutility::addaioverridedamagecallback@9a
DEVBLOCK 0x1b92
# aiutility::removeaioverridedamagecallback@42
DEVBLOCK 0x1d82
# aiutility::removeaioverridedamagecallback@6a
DEVBLOCK 0x1daa
# aiutility::removeaioverridedamagecallback@92
DEVBLOCK 0x1dd2
# aiutility::addaioverridekilledcallback@12
DEVBLOCK 0x1ec2
# aiutility::addaioverridekilledcallback@3a
DEVBLOCK 0x1eea
# aiutility::addaioverridekilledcallback@62
DEVBLOCK 0x1f12
