// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    setdvarifuninitialized( "_encstr_86E10F37B1C9AFEA6E2BEBE68BAB2CC89B", 1 );
    setdvarifuninitialized( "_encstr_BE180EDCC6C9F59BB857C232FAB6850F", 4 );
    setdvarifuninitialized( "_encstr_A1D715E6C64EBE6EB8BA2C467DC6592C462B27AF5B2CC3", 2 );
    setdvarifuninitialized( "_encstr_8C1617C7CF3EF161B01E32BA73D8AC49197F4B17CF65DB4808", "_encstr_A34C02BB" );
    setdvarifuninitialized( "_encstr_9B580EE6B139F5DC5BBDAD95E8B2378E", "_encstr_934C0218" );
    scripts\cp\utility::coop_mode_enable();
    registerscriptedagents();
    _encstr_A34F3D96F60BFB2B54D76A10C3D74023D31A20168A71979317F330A023BF597D6A47A8AEE2295F5B2F8B08581BC791B532EF68AFFA62C7E1FBC32B8227F329::main();
    _encstr_AB223C8F8706AA489043EDC61B726DE2DF3F76374938B306A14B770BB398AF8B3FB9EEAFDBD83ECB83B6EA930E38F5230ED74763BB75E18138FBB5DFA388::main();
    _encstr_9BDB376E1BC996E0479BE536E0BC6BB0076E5E8DE0EB6EECBEE095A393DEEC4EC223F2D883EB6ECEFAC1ACD139ED9D39858CFA66F0C5D9CD1B::main();
    setdvar( "_encstr_84D20BC8A9B7B51394314358D9", 1.25 );
    setdvar( "_encstr_83920A488F414D730D6721C8", 4 );
    setdvar( "_encstr_A5530B74088B11C93DE60105DE", 2048 );
    setdvar( "_encstr_91070B6BA23D9140AB28DFA4C4", 8 );
    setdvar( "_encstr_BE360B89A215A69A0AD229B47A", 8 );

    if ( level.createfx_enabled )
        return;

    scripts\common\vehicle::init_vehicles();
    scripts\cp\vehicle::init_vehicles();
    level.map_interaction_func = _encstr_8221411FB0AB6993E34EF6B2D85E8D1911C3FDDF3F31B7186713FDD3A308148D3119370EB9775333F7ABD9B55BC7A70B48B1EFA0857BF80D3109D4A857FBEFE0C498BA::register_interactions;
    level.custom_onspawnplayer_func = ::onplayerspawned;
    level.custom_onplayerconnect_func = ::onplayerconnect;
    level.weapon_rank_event_table = "_encstr_A5BB45120E23E98A53DB879931EF498EA33F2E90736F60A3C88903D82AC7091BD6FC973E83B7B00358A02D358377B1A23F4F09DC0289E0A0850247CA8481318D9D7D0945A75323";
    level.player_interaction_monitor = _encstr_8221411FB0AB6993E34EF6B2D85E8D1911C3FDDF3F31B7186713FDD3A308148D3119370EB9775333F7ABD9B55BC7A70B48B1EFA0857BF80D3109D4A857FBEFE0C498BA::level_specific_player_interaction_monitor;
    level.wait_for_interaction_func = _encstr_8221411FB0AB6993E34EF6B2D85E8D1911C3FDDF3F31B7186713FDD3A308148D3119370EB9775333F7ABD9B55BC7A70B48B1EFA0857BF80D3109D4A857FBEFE0C498BA::level_specific_wait_for_interaction_triggered;
    level.interaction_trigger_properties_func = ::interaction_trigger_properties;

    if ( !scripts\engine\utility::flag_exist( "_encstr_A65211EB562BA098E71253B95ABB589043B525" ) )
        scripts\engine\utility::flag_init( "_encstr_A65211EB562BA098E71253B95ABB589043B525" );

    if ( !scripts\engine\utility::flag_exist( "_encstr_BE9D114EEBD323808D9F90A06FB45E616A15CD" ) )
        scripts\engine\utility::flag_init( "_encstr_BE9D114EEBD323808D9F90A06FB45E616A15CD" );

    scripts\cp\cp_gameskill::init_gameskill();
    level thread wait_for_pre_game_period();
    level thread wait_for_strike_init_complete();
    level thread scripts\cp\cp_objectives::objectives_init();
    level thread scripts\cp\cp_movers::main();
    level thread scripts\cp\classes\cp_class_progression::class_progression_init();
    level thread scripts\cp\factions\faction_progression::faction_progression_init();
    level thread scripts\cp\cp_deployablebox::init();
    level.additional_laststand_weapon_exclusion = [];
    level thread setup_map_specific_devgui();
    setup_create_script();
    level.devgui_setup_func = ::onplayerspawneddevguisetup;

    if ( level.scripted_spawner_func.size < 1 )
        scripts\engine\utility::flag_set( "_encstr_BE9D114EEBD323808D9F90A06FB45E616A15CD" );

    if ( !scripts\engine\utility::flag_exist( "_encstr_A2D20FE4880D52A426C867576878654BD3" ) )
        scripts\engine\utility::flag_init( "_encstr_A2D20FE4880D52A426C867576878654BD3" );

    var_0 = getdvar( "_encstr_8F991A9677EF632EB6E0FFA3E868F7BB6B85110ADD3B2B54DE30EBD3", "_encstr_B40101" );

    if ( isdefined( var_0 ) && var_0 != "_encstr_B40101" )
        level thread rundebugstartobjective( var_0 );

    level.eogscoreboard = [ "_encstr_A19B0973B543C35FDDE063", "_encstr_8E8D0697EB01F243", "_encstr_96D30A3468575BA7C307A128", "_encstr_A9AB06297DDFD816", "_encstr_B642089B65A658E8F597" ];
    scripts\cp\cp_compass::setupminimap( "_encstr_B606199A7A28AAAA803E1FAD7FE91F97A17982654B23DD2F4E8BFB" );
    scripts\engine\utility::flag_set( "_encstr_A2D20FE4880D52A426C867576878654BD3" );
    thread player_fired_gun_monitor();
}

rundebugstartobjective( var_0 )
{
    wait 2;
    scripts\engine\utility::flag_wait( "_encstr_A2D20FE4880D52A426C867576878654BD3" );
    scripts\engine\utility::flag_wait( "_encstr_95D217A54E55D2EB03D84337513BA1EA0155211AA7CD0B35E9" );

    if ( isdefined( level.objectivestabledata[var_0] ) )
    {
        var_1 = level.objectivestabledata[var_0];

        if ( isdefined( var_1.ondebugstartfunc ) )
            [[ var_1.ondebugstartfunc ]]( var_1 );

        thread scripts\cp\cp_objectives::run_objective( var_1.objname, var_1.questtype );
    }
}

onplayerspawneddevguisetup( var_0 )
{
    var_1 = var_0.name;
    var_2 = undefined;

    foreach ( var_5, var_4 in level.players )
    {
        if ( var_4 == var_0 )
        {
            var_2 = int( var_5 );
            break;
        }
    }

    if ( isdefined( var_2 ) )
        var_0 thread setupdevguientries( var_0, var_1, var_2 );
}

setupdevguientries( var_0, var_1, var_2 )
{

}

wait_for_pre_game_period()
{
    if ( !isdefined( level.agent_funcs ) )
        level.agent_funcs = [];

    wait 0.2;
}

wait_for_strike_init_complete()
{
    level endon( "_encstr_9B1D0BC7932875276230426AA1" );
    scripts\engine\utility::flag_init( "_encstr_9B931F0EAC279B7BB916D87D95B9A3EB4FB7CDAC9BF52D9B968E4BB01B964F598C" );

    if ( scripts\engine\utility::flag_exist( "_encstr_BE9D114EEBD323808D9F90A06FB45E616A15CD" ) )
    {
        scripts\engine\utility::flag_wait( "_encstr_BE9D114EEBD323808D9F90A06FB45E616A15CD" );
        var_0 = getdvar( "_encstr_A70910FF7B8AE9B6DB23D098BA9FE0C0E5D5" );
        var_1 = undefined;

        switch ( var_0 )
        {
            case "_encstr_91CC11D3C3F9EA1AC8BE04606377DA1C3FF361":
                break;
            default:
                break;
        }
    }
}

registerscriptedagents()
{
    scripts\mp\mp_agent::init_agent( "_encstr_B16824CBD3E6A3A018F1A199A729F8692B074B573F5AF5199C57E910CD192813325B5DE78F03" );
    scripts\mp\agents\soldier\soldier_agent::registerscriptedagent();
    scripts\mp\agents\juggernaut\juggernaut_agent::registerscriptedagent();
}

onplayerconnect( var_0 )
{
    level thread bug_test_move_startpoint();
}

onplayerspawned()
{

}

bug_test_move_startpoint()
{
    if ( getdvarint( "_encstr_829910CF5E203138B80B9FF8309F40F9FFA4", 0 ) )
    {
        var_0 = scripts\engine\utility::getstructarray( "_encstr_977415C0B27F2B43438C503F7C9F0AFBA2B9C0C86A1249", "_encstr_B2CE0BA1D0FB19FDC54613D9BF" );

        foreach ( var_2 in var_0 )
        {
            var_2.origin = ( 3743, -1008, 384 );
            var_2.angles = ( 6, 265, 0 );
        }
    }
}

should_run_event( var_0 )
{
    return 0;
}

setup_map_specific_devgui()
{

}

interaction_trigger_properties( var_0, var_1, var_2 )
{
    switch ( var_1.script_noteworthy )
    {
        default:
            self.interaction_trigger setusefov( 360 );
            self.interaction_trigger sethintrequiresholding( 0 );

            if ( isdefined( var_1.useduration ) )
                self.interaction_trigger setuseholdduration( var_1.useduration );

            break;
    }
}

setup_create_script()
{
    level.threadedscriptspawners = 1;
    level.create_script_file_ids = [];
    level.cs_scripted_spawners = [];
    level.scripted_spawners = [];
    level.cs_scripted_spawners_triggers = [];
    level.scripted_spawners_triggers = [];
    level.cs_scripted_spawners_models = [];
    level.scripted_spawners_models = [];
    level.createscriptfilesinitialized = 0;
    level.scripted_spawner_func_strings = [];
    level.scripted_spawner_map_strings = [];
    level.scripted_spawner_func = [];
    register_create_script_arrays( "_encstr_959E1EFF91C05B1E99530F530B405703A7C187673D75A2D4A09E829E6358889B", "_encstr_959E1EFF91C05B1E99530F530B405703A7C187673D75A2D4A09E829E6358889B", level.scripted_spawner_func.size, _encstr_877C42CB5B0A605FFB939730B276D919D3ABBDA12A8E90C83F2097FB565217F3BF0A36205B97D3E0D79B558DEE5D0C904F2B208FDA2F0A7948D1FF5ADB1A03344E8F86D6::main );
}

register_create_script_arrays( var_0, var_1, var_2, var_3 )
{
    if ( isdefined( var_0 ) )
        level.scripted_spawner_func_strings[level.scripted_spawner_func_strings.size] = var_0;

    if ( isdefined( var_1 ) )
        level.scripted_spawner_map_strings[level.scripted_spawner_func_strings.size] = var_1;

    if ( isdefined( var_2 ) )
        level.create_script_file_ids[var_0] = "_encstr_8A0703D983" + var_2;

    if ( isdefined( var_3 ) )
        level.scripted_spawner_func[level.scripted_spawner_func.size] = var_3;
}

player_fired_gun_monitor()
{
    var_0 = getent( "_encstr_81A80E6B3128C3B29D326BF74AA1D85A", "_encstr_B2CE0BA1D0FB19FDC54613D9BF" );
    var_1 = spawn( "_encstr_82DC0DC6CB18BB5744B8C3978DEFB0", ( 1315, -2034, 216 ) );
    var_1.angles = ( 0, 0, 90 );
    var_1 clonebrushmodeltoscriptmodel( var_0 );
    var_0 = getent( "_encstr_81A80E6B3128C3B29D326BF74AA1D85A", "_encstr_B2CE0BA1D0FB19FDC54613D9BF" );
    var_1 = spawn( "_encstr_82DC0DC6CB18BB5744B8C3978DEFB0", ( 1315, -1955, 216 ) );
    var_1.angles = ( 0, 0, 90 );
    var_1 clonebrushmodeltoscriptmodel( var_0 );
    var_0 = getent( "_encstr_A9CD0EB1C62DC16C681E1BA18764A663", "_encstr_B2CE0BA1D0FB19FDC54613D9BF" );
    var_1 = spawn( "_encstr_82DC0DC6CB18BB5744B8C3978DEFB0", ( 1347, -1999, 42 ) );
    var_1.angles = ( 0, 0, 0 );
    var_1 clonebrushmodeltoscriptmodel( var_0 );
    var_0 = getent( "_encstr_825E11D8E2DFBB301C749B95D0C05ADE5A2B9A", "_encstr_B2CE0BA1D0FB19FDC54613D9BF" );
    var_1 = spawn( "_encstr_82DC0DC6CB18BB5744B8C3978DEFB0", ( -525, -1488, 216 ) );
    var_1.angles = ( 270, 270, 15 );
    var_1 clonebrushmodeltoscriptmodel( var_0 );
    var_0 = getent( "_encstr_825E11D8E2DFBB301C749B95D0C05ADE5A2B9A", "_encstr_B2CE0BA1D0FB19FDC54613D9BF" );
    var_1 = spawn( "_encstr_82DC0DC6CB18BB5744B8C3978DEFB0", ( -426, -1461.5, 216 ) );
    var_1.angles = ( 270, 270, 15 );
    var_1 clonebrushmodeltoscriptmodel( var_0 );
    var_2 = createnavobstaclebyshapeforlayer( ( -528, -1472, 152 ), 6, 32, 48 );
    var_3 = createnavbadplacebybounds( ( 1646.61, -5024.5, 230.22 ), ( 800, 800, 100 ), ( 0, 0, 0 ) );
}
