#using scripts\common\ai;
#using scripts\common\anim;
#using scripts\common\scene;
#using scripts\common\utility;
#using scripts\engine\sp\utility;
#using scripts\engine\utility;
#using scripts\sp\anim;
#using scripts\sp\utility;

#namespace namespace_ad892f5ce18e7e65;

// Namespace namespace_ad892f5ce18e7e65 / namespace_61685dfa35dc18a5
// Params 0
// Checksum 0x0, Offset: 0x724f
// Size: 0x17
function initanims()
{
    player();
    humans();
    vehicles();
}

// Namespace namespace_ad892f5ce18e7e65 / namespace_61685dfa35dc18a5
// Params 0, eflags: 0x4
// Checksum 0x0, Offset: 0x726e
// Size: 0x23
function private player()
{
    rigname = "player_rig";
    level.scr_model[ rigname ] = "vm_c_jup_sp_hero_price_tundra_diver";
}

#using_animtree( "generic_human" );

// Namespace namespace_ad892f5ce18e7e65 / namespace_61685dfa35dc18a5
// Params 0, eflags: 0x4
// Checksum 0x0, Offset: 0x7299
// Size: 0x2b13
function private humans()
{
    level.scr_anim[ "soap" ][ "reb_stl_alert_walk_react_sm_up_to_aimup" ] = %reb_stl_alert_walk_react_sm_up_to_aimup;
    level.scr_anim[ "corpse" ][ "deadbody_01" ][ 0 ] = %deadbody_01;
    level.scr_anim[ "corpse" ][ "deadbody_02" ][ 0 ] = %deadbody_02;
    level.scr_anim[ "corpse" ][ "deadbody_03" ][ 0 ] = %deadbody_03;
    level.scr_anim[ "corpse" ][ "deadbody_04" ][ 0 ] = %deadbody_04;
    level.scr_anim[ "corpse" ][ "deadbody_05" ][ 0 ] = %deadbody_05;
    level.scr_anim[ "corpse" ][ "deadbody_06" ][ 0 ] = %deadbody_06;
    level.scr_anim[ "corpse" ][ "deadbody_07" ][ 0 ] = %deadbody_07;
    level.scr_anim[ "corpse" ][ "deadbody_08" ][ 0 ] = %deadbody_08;
    level.scr_anim[ "corpse" ][ "deadbody_09" ][ 0 ] = %deadbody_09;
    level.scr_anim[ "corpse" ][ "deadbody_10" ][ 0 ] = %deadbody_10;
    level.scr_face[ "farah" ][ "dx_sp_tund_clif_fara_soareyougoldeagle" ] = %dx_sp_tund_clif_fara_soareyougoldeagle_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_fnex_fara_weneedtoleavebeforem" ] = %dx_sp_tund_fnex_fara_weneedtoleavebeforem_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_fnsg_fara_onyoucaptainexfilism" ] = %dx_sp_tund_fnsg_fara_onyoucaptainexfilism_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_fnsg_fara_weshouldgettoghostca" ] = %dx_sp_tund_fnsg_fara_weshouldgettoghostca_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_fnsn_fara_letsclearforexfilcap" ] = %dx_sp_tund_fnsn_fara_letsclearforexfilcap_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_fnsn_fara_stillhavetargetsinsi" ] = %dx_sp_tund_fnsn_fara_stillhavetargetsinsi_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_fnsn_fara_captainyouneedtoenga" ] = %dx_sp_tund_fnsn_fara_captainyouneedtoenga_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_fnsn_fara_captainpriceweneedyo" ] = %dx_sp_tund_fnsn_fara_captainpriceweneedyo_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_lmtp_fara_checkfiredescending" ] = %dx_sp_tund_lmtp_fara_checkfiredescending_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_lmtp_fara_exfilisjustbelowthis" ] = %dx_sp_tund_lmtp_fara_exfilisjustbelowthis_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_gotmovementahead" ] = %dx_sp_tund_shpy_fara_gotmovementahead_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_couldusetheopenwater" ] = %dx_sp_tund_shpy_fara_couldusetheopenwater_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_novisual" ] = %dx_sp_tund_shpy_fara_novisual_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_preparetoengage" ] = %dx_sp_tund_shpy_fara_preparetoengage_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_stayready" ] = %dx_sp_tund_shpy_fara_stayready_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_snowincoming" ] = %dx_sp_tund_shpy_fara_snowincoming_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_switchingtothermals" ] = %dx_sp_tund_shpy_fara_switchingtothermals_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_theycantseeusthrough" ] = %dx_sp_tund_shpy_fara_theycantseeusthrough_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_theyrefallingback" ] = %dx_sp_tund_shpy_fara_theyrefallingback_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_rpgseliminated" ] = %dx_sp_tund_shpy_fara_rpgseliminated_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_shipyardsallclear" ] = %dx_sp_tund_shpy_fara_shipyardsallclear_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_tglb_fara_exfilisthisway" ] = %dx_sp_tund_tglb_fara_exfilisthisway_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_tglb_fara_wedonthavemuchtime" ] = %dx_sp_tund_tglb_fara_wedonthavemuchtime_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_tglb_fara_exfilpointisthisway" ] = %dx_sp_tund_tglb_fara_exfilpointisthisway_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_clif_gazz_windspickingupsnow" ] = %dx_sp_tund_clif_gazz_windspickingupsnow_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnex_gazz_nikswaiting" ] = %dx_sp_tund_fnex_gazz_nikswaiting_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnex_gazz_captainweneedtogo" ] = %dx_sp_tund_fnex_gazz_captainweneedtogo_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnex_gazz_sixweneedtogo" ] = %dx_sp_tund_fnex_gazz_sixweneedtogo_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnsg_gazz_thelieutenantsholdin" ] = %dx_sp_tund_fnsg_gazz_thelieutenantsholdin_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnsg_gazz_exfilpointaheadonyou" ] = %dx_sp_tund_fnsg_gazz_exfilpointaheadonyou_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnsn_gazz_priceweneedyourgunon" ] = %dx_sp_tund_fnsn_gazz_priceweneedyourgunon_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnsn_gazz_needtoclearthelz" ] = %dx_sp_tund_fnsn_gazz_needtoclearthelz_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnsn_gazz_weneedyourgunonthisc" ] = %dx_sp_tund_fnsn_gazz_weneedyourgunonthisc_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnc1_gazz_eitherwayweneedacall" ] = %dx_sp_tund_fnc1_gazz_eitherwayweneedacall_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnc1_gazz_theyreonalert" ] = %dx_sp_tund_fnc1_gazz_theyreonalert_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnc1_gazz_theyheardus" ] = %dx_sp_tund_fnc1_gazz_theyheardus_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnc1_gazz_allclear" ] = %dx_sp_tund_fnc1_gazz_allclear_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnc1_gazz_whatsthecallcaptain" ] = %dx_sp_tund_fnc1_gazz_whatsthecallcaptain_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnc1_gazz_gothostilesclosingin" ] = %dx_sp_tund_fnc1_gazz_gothostilesclosingin_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnc1_gazz_konnispunchingupbehi" ] = %dx_sp_tund_fnc1_gazz_konnispunchingupbehi_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnc1_gazz_clear" ] = %dx_sp_tund_fnc1_gazz_clear_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnc1_gazz_whentheymisscheckins" ] = %dx_sp_tund_fnc1_gazz_whentheymisscheckins_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnc1_gazz_wouldntbetooproudoth" ] = %dx_sp_tund_fnc1_gazz_wouldntbetooproudoth_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_eyesonourtruckaheada" ] = %dx_sp_tund_ffld_gazz_eyesonourtruckaheada_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_wecouldslipbyifwehug" ] = %dx_sp_tund_ffld_gazz_wecouldslipbyifwehug_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_weremadeengage" ] = %dx_sp_tund_ffld_gazz_weremadeengage_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_vehicledestroyedther" ] = %dx_sp_tund_ffld_gazz_vehicledestroyedther_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_vehicledestryedwelos" ] = %dx_sp_tund_ffld_gazz_vehicledestryedwelos_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_goodeffectsnipersare" ] = %dx_sp_tund_ffld_gazz_goodeffectsnipersare_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_whatstheplancaptain" ] = %dx_sp_tund_ffld_gazz_whatstheplancaptain_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_capifyougotasniperri" ] = %dx_sp_tund_ffld_gazz_capifyougotasniperri_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_shitwerecompromised" ] = %dx_sp_tund_ffld_gazz_shitwerecompromised_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_theregoesourtranspor" ] = %dx_sp_tund_ffld_gazz_theregoesourtranspor_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_suppliesinsidearesti" ] = %dx_sp_tund_ffld_gazz_suppliesinsidearesti_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_goodkillcaptainthere" ] = %dx_sp_tund_ffld_gazz_goodkillcaptainthere_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_beadvisedbravomultip" ] = %dx_sp_tund_ffld_gazz_beadvisedbravomultip_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_goodshotonetogo" ] = %dx_sp_tund_ffld_gazz_goodshotonetogo_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_goodkillsironeleft" ] = %dx_sp_tund_ffld_gazz_goodkillsironeleft_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_themillsjustaheadalo" ] = %dx_sp_tund_ffld_gazz_themillsjustaheadalo_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_flashout" ] = %dx_sp_tund_ffld_gazz_flashout_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_throwingflashbang" ] = %dx_sp_tund_ffld_gazz_throwingflashbang_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_throwingstungrenade" ] = %dx_sp_tund_ffld_gazz_throwingstungrenade_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_stayfocusedactualsni" ] = %dx_sp_tund_ffld_gazz_stayfocusedactualsni_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_flushemoutofcover" ] = %dx_sp_tund_ffld_gazz_flushemoutofcover_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_getdownsix" ] = %dx_sp_tund_ffld_gazz_getdownsix_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_captaintakingeffecti" ] = %dx_sp_tund_ffld_gazz_captaintakingeffecti_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_findcovercaptainyouc" ] = %dx_sp_tund_ffld_gazz_findcovercaptainyouc_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_onexrayleft" ] = %dx_sp_tund_ffld_gazz_onexrayleft_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_wellrallyupwithfarah" ] = %dx_sp_tund_ffld_gazz_wellrallyupwithfarah_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_engagethemorslippast" ] = %dx_sp_tund_ffld_gazz_engagethemorslippast_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_cancutthroughthefiel" ] = %dx_sp_tund_ffld_gazz_cancutthroughthefiel_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fspr_gazz_anyonehavevisual" ] = %dx_sp_tund_fspr_gazz_anyonehavevisual_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fspr_gazz_nothingonthermals" ] = %dx_sp_tund_fspr_gazz_nothingonthermals_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fspr_gazz_rogerthatonmegeneral" ] = %dx_sp_tund_fspr_gazz_rogerthatonmegeneral_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fspr_gazz_rogercomintoya" ] = %dx_sp_tund_fspr_gazz_rogercomintoya_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fspr_gazz_rog" ] = %dx_sp_tund_fspr_gazz_rog_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fvta_gazz_camefromthelumbermil" ] = %dx_sp_tund_fvta_gazz_camefromthelumbermil_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fvta_gazz_theexplosionhappened" ] = %dx_sp_tund_fvta_gazz_theexplosionhappened_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fvta_gazz_millsthatway" ] = %dx_sp_tund_fvta_gazz_millsthatway_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fvta_gazz_farahwhatsyourstatus" ] = %dx_sp_tund_fvta_gazz_farahwhatsyourstatus_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fvta_gazz_farahswaitingcaptain" ] = %dx_sp_tund_fvta_gazz_farahswaitingcaptain_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fvta_gazz_copyapproachingwellh" ] = %dx_sp_tund_fvta_gazz_copyapproachingwellh_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fvta_gazz_rogpressingtothelumb" ] = %dx_sp_tund_fvta_gazz_rogpressingtothelumb_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fw1i_gazz_usuallyis" ] = %dx_sp_tund_fw1i_gazz_usuallyis_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fw1i_gazz_advisethermalcap" ] = %dx_sp_tund_fw1i_gazz_advisethermalcap_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fw1i_gazz_goodtimeforthermalsi" ] = %dx_sp_tund_fw1i_gazz_goodtimeforthermalsi_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fw1i_gazz_thermalonbravo" ] = %dx_sp_tund_fw1i_gazz_thermalonbravo_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fw1n_gazz_armoronthehelostoost" ] = %dx_sp_tund_fw1n_gazz_armoronthehelostoost_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fw1n_gazz_letssaveourbulletsfo" ] = %dx_sp_tund_fw1n_gazz_letssaveourbulletsfo_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fw1n_gazz_thatdbeahellofashotc" ] = %dx_sp_tund_fw1n_gazz_thatdbeahellofashotc_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fw1n_gazz_waitingonyousixwesho" ] = %dx_sp_tund_fw1n_gazz_waitingonyousixwesho_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fw1n_gazz_captainweshouldkeepp" ] = %dx_sp_tund_fw1n_gazz_captainweshouldkeepp_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fw1n_gazz_lumbermillsforwardof" ] = %dx_sp_tund_fw1n_gazz_lumbermillsforwardof_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_notanambushifwehitth" ] = %dx_sp_tund_shpy_gazz_notanambushifwehitth_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_letsgogeneral" ] = %dx_sp_tund_shpy_gazz_letsgogeneral_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_wecouldswimintotheop" ] = %dx_sp_tund_shpy_gazz_wecouldswimintotheop_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_justpointandshootwhe" ] = %dx_sp_tund_shpy_gazz_justpointandshootwhe_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_nothinyet" ] = %dx_sp_tund_shpy_gazz_nothinyet_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_nomovement" ] = %dx_sp_tund_shpy_gazz_nomovement_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_stitchemup" ] = %dx_sp_tund_shpy_gazz_stitchemup_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_thanksfortheassistca" ] = %dx_sp_tund_shpy_gazz_thanksfortheassistca_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_flurryscomingin" ] = %dx_sp_tund_shpy_gazz_flurryscomingin_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_thermalsup" ] = %dx_sp_tund_shpy_gazz_thermalsup_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_theyllloseusintheflu" ] = %dx_sp_tund_shpy_gazz_theyllloseusintheflu_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_morekonniclosing" ] = %dx_sp_tund_shpy_gazz_morekonniclosing_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_headsupenemyvehiclea" ] = %dx_sp_tund_shpy_gazz_headsupenemyvehiclea_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_keeppushingthemback" ] = %dx_sp_tund_shpy_gazz_keeppushingthemback_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_rpgsneutralized" ] = %dx_sp_tund_shpy_gazz_rpgsneutralized_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_tglb_gazz_weshouldpushtoexfilc" ] = %dx_sp_tund_tglb_gazz_weshouldpushtoexfilc_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_tglb_gazz_exfilwindowisclosing" ] = %dx_sp_tund_tglb_gazz_exfilwindowisclosing_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_alli_ghos_moreenemiesincomingn" ] = %dx_sp_tund_alli_ghos_moreenemiesincomingn_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_clif_ghos_allstationswehaveene" ] = %dx_sp_tund_clif_ghos_allstationswehaveene_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_clif_ghos_rogbringitonthen" ] = %dx_sp_tund_clif_ghos_rogbringitonthen_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_clif_ghos_wasntinthemoodforvis" ] = %dx_sp_tund_clif_ghos_wasntinthemoodforvis_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsg_ghos_ropinglzneartheboatn" ] = %dx_sp_tund_fnsg_ghos_ropinglzneartheboatn_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsg_ghos_thiswaybravo" ] = %dx_sp_tund_fnsg_ghos_thiswaybravo_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsg_ghos_movetothemarkprice" ] = %dx_sp_tund_fnsg_ghos_movetothemarkprice_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsg_ghos_holdinguphereforyous" ] = %dx_sp_tund_fnsg_ghos_holdinguphereforyous_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_gearuptheyllbemoreof" ] = %dx_sp_tund_fnsn_ghos_gearuptheyllbemoreof_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_gotmorekonnivehicles" ] = %dx_sp_tund_fnsn_ghos_gotmorekonnivehicles_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_stickclosetotheboat" ] = %dx_sp_tund_fnsn_ghos_stickclosetotheboat_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_meetbackattheboat" ] = %dx_sp_tund_fnsn_ghos_meetbackattheboat_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_needyouonstationcapt" ] = %dx_sp_tund_fnsn_ghos_needyouonstationcapt_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_laydownfire" ] = %dx_sp_tund_fnsn_ghos_laydownfire_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_priceweneedtoputfire" ] = %dx_sp_tund_fnsn_ghos_priceweneedtoputfire_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_niceshot" ] = %dx_sp_tund_fnsn_ghos_niceshot_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_nicework" ] = %dx_sp_tund_fnsn_ghos_nicework_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_niceone" ] = %dx_sp_tund_fnsn_ghos_niceone_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_konnivehiclesincomin" ] = %dx_sp_tund_fnsn_ghos_konnivehiclesincomin_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_stayneartheboat" ] = %dx_sp_tund_fnsn_ghos_stayneartheboat_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnsn_ghos_priceweneedfocusedfi" ] = %dx_sp_tund_fnsn_ghos_priceweneedfocusedfi_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fspr_ghos_copylzissecurewillre" ] = %dx_sp_tund_fspr_ghos_copylzissecurewillre_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fw1i_ghos_copyfarahtakesthemil" ] = %dx_sp_tund_fw1i_ghos_copyfarahtakesthemil_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_outi_niko_thatsnotthepassenger" ] = %dx_sp_tund_outi_niko_thatsnotthepassenger_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_outi_niko_everyonesonboardlasw" ] = %dx_sp_tund_outi_niko_everyonesonboardlasw_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnex_shep_weneedtogetthisbirdi" ] = %dx_sp_tund_fnex_shep_weneedtogetthisbirdi_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnex_shep_itistimetogocapn" ] = %dx_sp_tund_fnex_shep_itistimetogocapn_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnex_shep_getaboardjohn" ] = %dx_sp_tund_fnex_shep_getaboardjohn_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnsn_shep_sticktotheboatjohn" ] = %dx_sp_tund_fnsn_shep_sticktotheboatjohn_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnsn_shep_coulduseyoursupporta" ] = %dx_sp_tund_fnsn_shep_coulduseyoursupporta_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnsn_shep_theysentawholegoddam" ] = %dx_sp_tund_fnsn_shep_theysentawholegoddam_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnsn_shep_weneedaclearhlz" ] = %dx_sp_tund_fnsn_shep_weneedaclearhlz_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnsn_shep_needyourguntoclearth" ] = %dx_sp_tund_fnsn_shep_needyourguntoclearth_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnsn_shep_letskillthesekonnisu" ] = %dx_sp_tund_fnsn_shep_letskillthesekonnisu_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnsn_shep_stayinthisgunfightca" ] = %dx_sp_tund_fnsn_shep_stayinthisgunfightca_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnc1_shep_theyrelookingforme" ] = %dx_sp_tund_fnc1_shep_theyrelookingforme_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnc1_shep_weshouldtakeemoutnow" ] = %dx_sp_tund_fnc1_shep_weshouldtakeemoutnow_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnc1_shep_shouldveengagedalrea" ] = %dx_sp_tund_fnc1_shep_shouldveengagedalrea_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnc1_shep_shouldvekilledthemwh" ] = %dx_sp_tund_fnc1_shep_shouldvekilledthemwh_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fnc1_shep_igotcaughtbecauseiwa" ] = %dx_sp_tund_fnc1_shep_igotcaughtbecauseiwa_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_ffld_shep_smartmoveson" ] = %dx_sp_tund_ffld_shep_smartmoveson_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_ffld_shep_doesapolarbearshitin" ] = %dx_sp_tund_ffld_shep_doesapolarbearshitin_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_ffld_shep_countonit" ] = %dx_sp_tund_ffld_shep_countonit_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_ffld_shep_thispistolwontcutity" ] = %dx_sp_tund_ffld_shep_thispistolwontcutity_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_ffld_shep_takecoversir" ] = %dx_sp_tund_ffld_shep_takecoversir_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_ffld_shep_captainshitrepositio" ] = %dx_sp_tund_ffld_shep_captainshitrepositio_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_ffld_shep_expectednothinglessp" ] = %dx_sp_tund_ffld_shep_expectednothinglessp_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_ffld_shep_goodjobyoulostyourtr" ] = %dx_sp_tund_ffld_shep_goodjobyoulostyourtr_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fspr_shep_howfaristhetransport" ] = %dx_sp_tund_fspr_shep_howfaristhetransport_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fspr_shep_myintelsalwaysgoodso" ] = %dx_sp_tund_fspr_shep_myintelsalwaysgoodso_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fvta_shep_idontneedachaperonej" ] = %dx_sp_tund_fvta_shep_idontneedachaperonej_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fvta_shep_gotweaponsherejohn" ] = %dx_sp_tund_fvta_shep_gotweaponsherejohn_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fw1i_shep_imfreezingmyassofher" ] = %dx_sp_tund_fw1i_shep_imfreezingmyassofher_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_fw1i_shep_youneedadisciplinead" ] = %dx_sp_tund_fw1i_shep_youneedadisciplinead_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_lmtp_shep_gearupinhere" ] = %dx_sp_tund_lmtp_shep_gearupinhere_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_lmtp_shep_soapswaitingonyouout" ] = %dx_sp_tund_lmtp_shep_soapswaitingonyouout_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_lmtp_shep_resupplyandgetbackou" ] = %dx_sp_tund_lmtp_shep_resupplyandgetbackou_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_lmtp_shep_imnotgoinganywherejo" ] = %dx_sp_tund_lmtp_shep_imnotgoinganywherejo_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_lmtp_shep_yourealongwayfromhom" ] = %dx_sp_tund_lmtp_shep_yourealongwayfromhom_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_shpy_shep_likelyanambush" ] = %dx_sp_tund_shpy_shep_likelyanambush_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_shpy_shep_theresfissuresinthei" ] = %dx_sp_tund_shpy_shep_theresfissuresinthei_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_shpy_shep_feelsgoodtobebehindt" ] = %dx_sp_tund_shpy_shep_feelsgoodtobebehindt_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_shpy_shep_nothinglikehuntinthe" ] = %dx_sp_tund_shpy_shep_nothinglikehuntinthe_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_shpy_shep_everybodyready" ] = %dx_sp_tund_shpy_shep_everybodyready_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_shpy_shep_elementofsurpriseiso" ] = %dx_sp_tund_shpy_shep_elementofsurpriseiso_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_shpy_shep_fireatwill" ] = %dx_sp_tund_shpy_shep_fireatwill_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_shpy_shep_thatllkillyourvisibi" ] = %dx_sp_tund_shpy_shep_thatllkillyourvisibi_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_shpy_shep_gottheupperhandnow" ] = %dx_sp_tund_shpy_shep_gottheupperhandnow_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_shpy_shep_thatrpgsisoutgoodwor" ] = %dx_sp_tund_shpy_shep_thatrpgsisoutgoodwor_face;
    level.scr_face[ "shepherd" ][ "dx_sp_tund_shpy_shep_thisisntoveruntilwer" ] = %dx_sp_tund_shpy_shep_thisisntoveruntilwer_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_clif_soap_lookslikekonnidroppe" ] = %dx_sp_tund_clif_soap_lookslikekonnidroppe_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnex_soap_letsgocaptain" ] = %dx_sp_tund_fnex_soap_letsgocaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnsg_soap_spottedeyesonlt" ] = %dx_sp_tund_fnsg_soap_spottedeyesonlt_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnsg_soap_readywhenyouaresir" ] = %dx_sp_tund_fnsg_soap_readywhenyouaresir_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnsg_soap_ghostswaitingonussix" ] = %dx_sp_tund_fnsg_soap_ghostswaitingonussix_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnsg_soap_letsnotstickaroundca" ] = %dx_sp_tund_fnsg_soap_letsnotstickaroundca_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnsn_soap_needtoshootthesebast" ] = %dx_sp_tund_fnsn_soap_needtoshootthesebast_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnsn_soap_clearthelz" ] = %dx_sp_tund_fnsn_soap_clearthelz_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnsn_soap_helpusburythesebasta" ] = %dx_sp_tund_fnsn_soap_helpusburythesebasta_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnc1_soap_konihelodroppedinsom" ] = %dx_sp_tund_fnc1_soap_konihelodroppedinsom_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnc1_soap_youshouldshutthehell" ] = %dx_sp_tund_fnc1_soap_youshouldshutthehell_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnc1_soap_theydontseeusbutthey" ] = %dx_sp_tund_fnc1_soap_theydontseeusbutthey_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnc1_soap_quiet" ] = %dx_sp_tund_fnc1_soap_quiet_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnc1_soap_stayhiddenunlessweag" ] = %dx_sp_tund_fnc1_soap_stayhiddenunlessweag_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnc1_soap_gotanothersquadclosi" ] = %dx_sp_tund_fnc1_soap_gotanothersquadclosi_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnc1_soap_ideaistogetclosewith" ] = %dx_sp_tund_fnc1_soap_ideaistogetclosewith_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fnc1_soap_theyremovingonweclea" ] = %dx_sp_tund_fnc1_soap_theyremovingonweclea_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_affirmassaultteam" ] = %dx_sp_tund_ffld_soap_affirmassaultteam_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_transportsgotammoand" ] = %dx_sp_tund_ffld_soap_transportsgotammoand_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_grenadestandclear" ] = %dx_sp_tund_ffld_soap_grenadestandclear_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_grenadetakecover" ] = %dx_sp_tund_ffld_soap_grenadetakecover_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_headsupsnipersaresti" ] = %dx_sp_tund_ffld_soap_headsupsnipersaresti_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_vehiclestoast" ] = %dx_sp_tund_ffld_soap_vehiclestoast_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_theenginesgrilled" ] = %dx_sp_tund_ffld_soap_theenginesgrilled_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_trucksfullofweaponsa" ] = %dx_sp_tund_ffld_soap_trucksfullofweaponsa_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_needalongerrangerifl" ] = %dx_sp_tund_ffld_soap_needalongerrangerifl_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_flashout" ] = %dx_sp_tund_ffld_soap_flashout_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_deployingstungrenade" ] = %dx_sp_tund_ffld_soap_deployingstungrenade_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_throwingflash" ] = %dx_sp_tund_ffld_soap_throwingflash_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_sniperscouldbeanywhe" ] = %dx_sp_tund_ffld_soap_sniperscouldbeanywhe_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_theyrehidingbuttheyr" ] = %dx_sp_tund_ffld_soap_theyrehidingbuttheyr_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_getoutofthereactual" ] = %dx_sp_tund_ffld_soap_getoutofthereactual_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_gettocovercaptain" ] = %dx_sp_tund_ffld_soap_gettocovercaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_staylowsiryouneedtol" ] = %dx_sp_tund_ffld_soap_staylowsiryouneedtol_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ffld_soap_speakinmylanguagegaz" ] = %dx_sp_tund_ffld_soap_speakinmylanguagegaz_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_negative" ] = %dx_sp_tund_fspr_soap_negative_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_nevergowrongtakinthe" ] = %dx_sp_tund_fspr_soap_nevergowrongtakinthe_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_tacticallyadvantageo" ] = %dx_sp_tund_fspr_soap_tacticallyadvantageo_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_birdseyegoodmovesir" ] = %dx_sp_tund_fspr_soap_birdseyegoodmovesir_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_bastardshiding" ] = %dx_sp_tund_fspr_soap_bastardshiding_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_konnisniperisrelocat" ] = %dx_sp_tund_fspr_soap_konnisniperisrelocat_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_snipersonthemove" ] = %dx_sp_tund_fspr_soap_snipersonthemove_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_enemysnipersrepositi" ] = %dx_sp_tund_fspr_soap_enemysnipersrepositi_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_hesstunnedlightemup" ] = %dx_sp_tund_fspr_soap_hesstunnedlightemup_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_flashbanggothimtakeh" ] = %dx_sp_tund_fspr_soap_flashbanggothimtakeh_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_snipersstunneddrophi" ] = %dx_sp_tund_fspr_soap_snipersstunneddrophi_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_negativelooking" ] = %dx_sp_tund_fspr_soap_negativelooking_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_hesgottabeclose" ] = %dx_sp_tund_fspr_soap_hesgottabeclose_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_soaptoghostwereafewm" ] = %dx_sp_tund_fspr_soap_soaptoghostwereafewm_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_thisisafuckinshitsho" ] = %dx_sp_tund_fspr_soap_thisisafuckinshitsho_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_getdown" ] = %dx_sp_tund_fspr_soap_getdown_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_hesseesyousir" ] = %dx_sp_tund_fspr_soap_hesseesyousir_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_findcoveractual" ] = %dx_sp_tund_fspr_soap_findcoveractual_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_hesgotyousightedcapt" ] = %dx_sp_tund_fspr_soap_hesgotyousightedcapt_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_sniperswoundedcaptai" ] = %dx_sp_tund_fspr_soap_sniperswoundedcaptai_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_gladly" ] = %dx_sp_tund_fspr_soap_gladly_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_niceworkcaptain" ] = %dx_sp_tund_fspr_soap_niceworkcaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fspr_soap_sniperdownwereclears" ] = %dx_sp_tund_fspr_soap_sniperdownwereclears_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_hearthat" ] = %dx_sp_tund_fvta_soap_hearthat_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_comeinkilo" ] = %dx_sp_tund_fvta_soap_comeinkilo_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_farahsupahead" ] = %dx_sp_tund_fvta_soap_farahsupahead_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_letsjointhefightcapt" ] = %dx_sp_tund_fvta_soap_letsjointhefightcapt_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_farahneedsbackupbrav" ] = %dx_sp_tund_fvta_soap_farahneedsbackupbrav_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_wereneededatthemills" ] = %dx_sp_tund_fvta_soap_wereneededatthemills_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_needtogetinthereclos" ] = %dx_sp_tund_fvta_soap_needtogetinthereclos_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_letsgetupcloseforthi" ] = %dx_sp_tund_fvta_soap_letsgetupcloseforthi_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_werenoteffectivefrom" ] = %dx_sp_tund_fvta_soap_werenoteffectivefrom_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_watchthatedgesirlong" ] = %dx_sp_tund_fvta_soap_watchthatedgesirlong_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_thatwaysriskyactuall" ] = %dx_sp_tund_fvta_soap_thatwaysriskyactuall_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fvta_soap_bravo6advisetakingth" ] = %dx_sp_tund_fvta_soap_bravo6advisetakingth_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1i_soap_laswellsright" ] = %dx_sp_tund_fw1i_soap_laswellsright_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1i_soap_fogsrollingin" ] = %dx_sp_tund_fw1i_soap_fogsrollingin_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1i_soap_gazisrightusethermal" ] = %dx_sp_tund_fw1i_soap_gazisrightusethermal_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1i_soap_uptoyousirbutthermal" ] = %dx_sp_tund_fw1i_soap_uptoyousirbutthermal_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1i_soap_slightcaseohypotherm" ] = %dx_sp_tund_fw1i_soap_slightcaseohypotherm_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_wedonthavetherangeon" ] = %dx_sp_tund_fw1n_soap_wedonthavetherangeon_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_nousecaptainhelostoo" ] = %dx_sp_tund_fw1n_soap_nousecaptainhelostoo_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_wedonthavetherangeca" ] = %dx_sp_tund_fw1n_soap_wedonthavetherangeca_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_allbravoexfilvehicle" ] = %dx_sp_tund_fw1n_soap_allbravoexfilvehicle_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_sixweneedtogettothet" ] = %dx_sp_tund_fw1n_soap_sixweneedtogettothet_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_transportsjustaheadc" ] = %dx_sp_tund_fw1n_soap_transportsjustaheadc_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_konniincomingwecantw" ] = %dx_sp_tund_fw1n_soap_konniincomingwecantw_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_weshouldgettothetruc" ] = %dx_sp_tund_fw1n_soap_weshouldgettothetruc_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_wegottahikeupriver" ] = %dx_sp_tund_fw1n_soap_wegottahikeupriver_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_farahswaitingforusat" ] = %dx_sp_tund_fw1n_soap_farahswaitingforusat_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_farahsheadedtothelum" ] = %dx_sp_tund_fw1n_soap_farahsheadedtothelum_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_fw1n_soap_millsupriverfarahsth" ] = %dx_sp_tund_fw1n_soap_millsupriverfarahsth_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ldet_soap_visual" ] = %dx_sp_tund_ldet_soap_visual_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ldet_soap_allstationsnojoynega" ] = %dx_sp_tund_ldet_soap_allstationsnojoynega_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_ldet_soap_bravotowatchernoeffe" ] = %dx_sp_tund_ldet_soap_bravotowatchernoeffe_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lkmn_soap_allstationsgoodeffec" ] = %dx_sp_tund_lkmn_soap_allstationsgoodeffec_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lkmn_soap_xraydownmovingtonext" ] = %dx_sp_tund_lkmn_soap_xraydownmovingtonext_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lkmn_soap_wegottamovecaptainma" ] = %dx_sp_tund_lkmn_soap_wegottamovecaptainma_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lkmn_soap_gottamoveontargetcap" ] = %dx_sp_tund_lkmn_soap_gottamoveontargetcap_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lkmn_soap_bravo6clockstickinwe" ] = %dx_sp_tund_lkmn_soap_bravo6clockstickinwe_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lkmn_soap_vehiclesclearnomakar" ] = %dx_sp_tund_lkmn_soap_vehiclesclearnomakar_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lkmn_soap_thisonesclear" ] = %dx_sp_tund_lkmn_soap_thisonesclear_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lrsc_soap_rog" ] = %dx_sp_tund_lrsc_soap_rog_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lrsc_soap_nomakarovjustaprison" ] = %dx_sp_tund_lrsc_soap_nomakarovjustaprison_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lrsc_soap_prisonerisontheleftc" ] = %dx_sp_tund_lrsc_soap_prisonerisontheleftc_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lrsc_soap_bravo6leftsideforext" ] = %dx_sp_tund_lrsc_soap_bravo6leftsideforext_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_aye" ] = %dx_sp_tund_lmtp_soap_aye_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_affirmativesirletsgi" ] = %dx_sp_tund_lmtp_soap_affirmativesirletsgi_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_moreenemiesaheadcapt" ] = %dx_sp_tund_lmtp_soap_moreenemiesaheadcapt_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_pushinguponyousir" ] = %dx_sp_tund_lmtp_soap_pushinguponyousir_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_morehostilesahead" ] = %dx_sp_tund_lmtp_soap_morehostilesahead_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_gotroundscominfromth" ] = %dx_sp_tund_lmtp_soap_gotroundscominfromth_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_makarovsgotmanpoweri" ] = %dx_sp_tund_lmtp_soap_makarovsgotmanpoweri_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_gotanenemyvehicleinb" ] = %dx_sp_tund_lmtp_soap_gotanenemyvehicleinb_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_youtookilo" ] = %dx_sp_tund_lmtp_soap_youtookilo_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_moreenemiesincoming" ] = %dx_sp_tund_lmtp_soap_moreenemiesincoming_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_movingaheadtoexfil" ] = %dx_sp_tund_lmtp_soap_movingaheadtoexfil_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_clearareasecure" ] = %dx_sp_tund_lmtp_soap_clearareasecure_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lmtp_soap_letsregroupwithkiloc" ] = %dx_sp_tund_lmtp_soap_letsregroupwithkiloc_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_onthemove" ] = %dx_sp_tund_shpy_soap_onthemove_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_crackintheicecouldma" ] = %dx_sp_tund_shpy_soap_crackintheicecouldma_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_somebodytapehisheads" ] = %dx_sp_tund_shpy_soap_somebodytapehisheads_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_nothingonthermals" ] = %dx_sp_tund_shpy_soap_nothingonthermals_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_theyregettinreadytop" ] = %dx_sp_tund_shpy_soap_theyregettinreadytop_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_sneakybastards" ] = %dx_sp_tund_shpy_soap_sneakybastards_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_niceshotsir" ] = %dx_sp_tund_shpy_soap_niceshotsir_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_rightontargetcaptain" ] = %dx_sp_tund_shpy_soap_rightontargetcaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_goodhitsix" ] = %dx_sp_tund_shpy_soap_goodhitsix_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_quickanddirtycaptain" ] = %dx_sp_tund_shpy_soap_quickanddirtycaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_shoottokill" ] = %dx_sp_tund_shpy_soap_shoottokill_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_windspickingup" ] = %dx_sp_tund_shpy_soap_windspickingup_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_rogerthermals" ] = %dx_sp_tund_shpy_soap_rogerthermals_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_usethesnowforcover" ] = %dx_sp_tund_shpy_soap_usethesnowforcover_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_theyrepushingupwithr" ] = %dx_sp_tund_shpy_soap_theyrepushingupwithr_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_theirranksarethinnin" ] = %dx_sp_tund_shpy_soap_theirranksarethinnin_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_rpgisdownandout" ] = %dx_sp_tund_shpy_soap_rpgisdownandout_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_tglb_soap_ghostswaitingatexfil" ] = %dx_sp_tund_tglb_soap_ghostswaitingatexfil_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_tglb_soap_exfilisntfarsir" ] = %dx_sp_tund_tglb_soap_exfilisntfarsir_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_tglb_soap_ivegotammo" ] = %dx_sp_tund_tglb_soap_ivegotammo_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_tglb_soap_ammohere" ] = %dx_sp_tund_tglb_soap_ammohere_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_tglb_soap_ihaveammohere" ] = %dx_sp_tund_tglb_soap_ihaveammohere_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_sniperslyingprone" ] = %dx_sp_tund_ffld_gazz_sniperslyingprone_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_ffld_gazz_gotasniperinthetrees" ] = %dx_sp_tund_ffld_gazz_gotasniperinthetrees_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_fnex_niko_touchingdowninthirty" ] = %dx_sp_tund_fnex_niko_touchingdowninthirty_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_fnex_niko_cominginhot" ] = %dx_sp_tund_fnex_niko_cominginhot_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_fnex_niko_looksliketheressomes" ] = %dx_sp_tund_fnex_niko_looksliketheressomes_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_fnex_niko_landed" ] = %dx_sp_tund_fnex_niko_landed_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_fnex_niko_readywhenyouarecapta" ] = %dx_sp_tund_fnex_niko_readywhenyouarecapta_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_fnex_niko_getincaptain" ] = %dx_sp_tund_fnex_niko_getincaptain_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_fnex_niko_copyapproachingnowca" ] = %dx_sp_tund_fnex_niko_copyapproachingnowca_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_fnex_niko_youstillhavecontactb" ] = %dx_sp_tund_fnex_niko_youstillhavecontactb_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_fnex_niko_touchdown" ] = %dx_sp_tund_fnex_niko_touchdown_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_fnex_niko_comeoncaptain" ] = %dx_sp_tund_fnex_niko_comeoncaptain_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_fnex_niko_letsgosix" ] = %dx_sp_tund_fnex_niko_letsgosix_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_outi_niko_allin" ] = %dx_sp_tund_outi_niko_allin_face;
    level.scr_face[ "nikolai" ][ "dx_sp_tund_outi_niko_laswellsixondeckwere" ] = %dx_sp_tund_outi_niko_laswellsixondeckwere_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_lkmn_soap_actuallovetolethimdr" ] = %dx_sp_tund_lkmn_soap_actuallovetolethimdr_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_morekonnigunnerscomi" ] = %dx_sp_tund_shpy_soap_morekonnigunnerscomi_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_goodhitcaptain" ] = %dx_sp_tund_shpy_fara_goodhitcaptain_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_goodeffectactual" ] = %dx_sp_tund_shpy_fara_goodeffectactual_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_goodkillcaptain" ] = %dx_sp_tund_shpy_fara_goodkillcaptain_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_theyresendingmoretro" ] = %dx_sp_tund_shpy_fara_theyresendingmoretro_face;
    level.scr_face[ "farah" ][ "dx_sp_tund_shpy_fara_youvegotmoreenemyrei" ] = %dx_sp_tund_shpy_fara_youvegotmoreenemyrei_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_fnsn_gazz_theyreflankingus" ] = %dx_sp_tund_fnsn_gazz_theyreflankingus_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_takingeffectivefirea" ] = %dx_sp_tund_shpy_gazz_takingeffectivefirea_face;
    level.scr_face[ "gaz" ][ "dx_sp_tund_shpy_gazz_enemyreinforcementsi" ] = %dx_sp_tund_shpy_gazz_enemyreinforcementsi_face;
    level.scr_face[ "ghost" ][ "dx_sp_tund_fnex_ghos_clear" ] = %dx_sp_tund_fnex_ghos_clear_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_takinheatfromthecarg" ] = %dx_sp_tund_shpy_soap_takinheatfromthecarg_face;
    level.scr_face[ "soap" ][ "dx_sp_tund_shpy_soap_rpgsupahead" ] = %dx_sp_tund_shpy_soap_rpgsupahead_face;
}

#using_animtree( "vehicles" );

// Namespace namespace_ad892f5ce18e7e65 / namespace_61685dfa35dc18a5
// Params 0, eflags: 0x4
// Checksum 0x0, Offset: 0x9db4
// Size: 0x64
function private vehicles()
{
    level.scr_animtree[ "finale_exfil_heli" ] = #animtree;
    level.scr_animtree[ "lumbermill_jltv" ] = #animtree;
    level.scr_anim[ "finale_jltv_turret" ][ "flip" ] = %cnv_jockey_jltv_turret_vehphys_flip;
    level.scr_anim[ "lumbermill_jltv" ][ "fishtail" ] = %jup_tun_jockey_car_fishtail;
}

