#using scripts\common\anim;
#using scripts\common\utility;
#using scripts\engine\sp\utility;
#using scripts\sp\anim;
#using scripts\sp\utility;

#namespace namespace_4ef95c8017583719;

// Namespace namespace_4ef95c8017583719 / namespace_2d132edcaaf1f5af
// Params 0
// Checksum 0x0, Offset: 0x6b06
// Size: 0x17
function main()
{
    ai_anims();
    player_anims();
    init_anim_script_model();
}

#using_animtree( "generic_human" );

// Namespace namespace_4ef95c8017583719 / namespace_2d132edcaaf1f5af
// Params 0
// Checksum 0x0, Offset: 0x6b25
// Size: 0x3689
function ai_anims()
{
    level.scr_anim[ "generic" ][ "dup_est_search_cabinet_terry_death" ] = %dup_est_search_cabinet_terry_death;
    level.scr_anim[ "generic" ][ "dup_est_search_desk_terry_death_back" ] = %dup_est_search_desk_terry_death_back;
    level.scr_anim[ "generic" ][ "lon_intersect_civ06_idle" ][ 0 ] = %lon_intersect_civ06_idle;
    level.scr_anim[ "generic" ][ "reb_stl_idle_stand_smoking" ][ 0 ] = %reb_stl_idle_stand_smoking;
    level.scr_anim[ "generic" ][ "civ_suspicious_walk02_man01" ] = %civ_suspicious_walk02_man01;
    level.scr_anim[ "generic" ][ "civ_suspicious_walk02_man02" ] = %civ_suspicious_walk02_man02;
    level.scr_anim[ "generic" ][ "civ_suspicious_walk03_man01" ] = %civ_suspicious_walk03_man01;
    level.scr_anim[ "generic" ][ "civ_suspicious_walk03_man02" ] = %civ_suspicious_walk03_man02;
    level.scr_anim[ "generic" ][ "civ_suspicious_walk04_man01" ] = %civ_suspicious_walk04_man01;
    level.scr_anim[ "generic" ][ "civ_suspicious_walk04_man02" ] = %civ_suspicious_walk04_man02;
    level.scr_anim[ "generic" ][ "jup_interaction_patrol_tablet_scanning_loop_01" ][ 0 ] = %jup_interaction_patrol_tablet_scanning_loop_01;
    level.scr_anim[ "generic" ][ "grd_stl_patrol_stand_humming01_idle" ][ 0 ] = %grd_stl_patrol_stand_humming01_idle;
    level.scr_anim[ "generic" ][ "jup_interaction_patrol_tying_shoe_loop_01" ][ 0 ] = %jup_interaction_patrol_tying_shoe_loop_01;
    level.scr_anim[ "generic" ][ "grd_stl_patrol_stand_cellphone_idle01" ][ 0 ] = %grd_stl_patrol_stand_cellphone_idle01;
    level.scr_anim[ "generic" ][ "grd_stl_patrol_stand_cellphone_idle02" ][ 0 ] = %grd_stl_patrol_stand_cellphone_idle02;
    level.scr_anim[ "generic" ][ "grd_stl_patrol_stand_waterbottle_idle01" ][ 0 ] = %grd_stl_patrol_stand_waterbottle_idle01;
    level.scr_anim[ "generic" ][ "grd_stl_patrol_stand_radio_idle01" ][ 0 ] = %grd_stl_patrol_stand_radio_idle01;
    level.scr_anim[ "generic" ][ "grd_stl_patrol_stand_radio_idle02" ][ 0 ] = %grd_stl_patrol_stand_radio_idle02;
    level.scr_anim[ "generic" ][ "grd_stl_patrol_stand_rub_hand_idle01" ][ 0 ] = %grd_stl_patrol_stand_rub_hand_idle01;
    level.scr_anim[ "generic" ][ "grd_stl_patrol_stand_rub_hand_idle04" ][ 0 ] = %grd_stl_patrol_stand_rub_hand_idle04;
    level.scr_anim[ "generic" ][ "emb_def_civ_point_a_Idle_civ02" ][ 0 ] = %emb_def_civ_point_a_idle_civ02;
    level.scr_anim[ "generic" ][ "emb_infil_030_offices_idle_civ03" ][ 0 ] = %emb_infil_030_offices_idle_civ03;
    level.scr_anim[ "generic" ][ "emb_infil_030_offices_idle_civ12" ][ 0 ] = %emb_infil_030_offices_idle_civ12;
    level.scr_anim[ "generic" ][ "emb_infil_030_offices_idle_civ14" ][ 0 ] = %emb_infil_030_offices_idle_civ14;
    level.scr_anim[ "generic" ][ "emb_res_015_dejected_idle_civ01" ][ 0 ] = %emb_res_015_dejected_idle_civ01;
    level.scr_anim[ "generic" ][ "emb_res_015_dejected_idle_civ02" ][ 0 ] = %emb_res_015_dejected_idle_civ02;
    level.scr_anim[ "generic" ][ "emb_res_015_dejected_idle_civ03" ][ 0 ] = %emb_res_015_dejected_idle_civ03;
    level.scr_anim[ "generic" ][ "emb_res_015_dejected_idle_civ04" ][ 0 ] = %emb_res_015_dejected_idle_civ04;
    level.scr_anim[ "generic" ][ "emb_res_015_dejected_idle_civ05" ][ 0 ] = %emb_res_015_dejected_idle_civ05;
    level.scr_anim[ "generic" ][ "emb_res_015_dejected_idle_civ06" ][ 0 ] = %emb_res_015_dejected_idle_civ06;
    level.scr_anim[ "generic" ][ "lon_intersect_civ03_idle" ][ 0 ] = %lon_intersect_civ03_idle;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_02_FA_k" ][ 0 ] = %ped_idle_casual_rain_group_02_fa_k;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_01_MA_m" ][ 0 ] = %ped_idle_casual_rain_group_01_ma_m;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_02_MD_m" ][ 0 ] = %ped_idle_casual_rain_group_02_md_m;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_02_MF_j" ][ 0 ] = %ped_idle_casual_rain_group_02_mf_j;
    level.scr_anim[ "generic" ][ "SH_020_marketplace_reactF_civ04" ][ 0 ] = %sh_020_marketplace_reactf_civ04;
    level.scr_anim[ "generic" ][ "SH_020_marketplace_reactF_civ05" ][ 0 ] = %sh_020_marketplace_reactf_civ05;
    level.scr_anim[ "generic" ][ "SH_020_marketplace_reactL_civ04" ][ 0 ] = %sh_020_marketplace_reactl_civ04;
    level.scr_anim[ "generic" ][ "SH_020_marketplace_reactL_civ05" ][ 0 ] = %sh_020_marketplace_reactl_civ05;
    level.scr_anim[ "generic" ][ "SH_020_marketplace_talkF_civ04" ][ 0 ] = %sh_020_marketplace_talkf_civ04;
    level.scr_anim[ "generic" ][ "SH_020_marketplace_talkF_civ05" ][ 0 ] = %sh_020_marketplace_talkf_civ05;
    level.scr_anim[ "generic" ][ "SH_020_marketplace_reactR_civ04" ][ 0 ] = %sh_020_marketplace_reactr_civ04;
    level.scr_anim[ "generic" ][ "SH_020_marketplace_reactR_civ05" ][ 0 ] = %sh_020_marketplace_reactr_civ05;
    level.scr_anim[ "generic" ][ "lon_intersect_civ04_idle" ][ 0 ] = %lon_intersect_civ04_idle;
    level.scr_anim[ "generic" ][ "lon_intersect_civ05_idle" ][ 0 ] = %lon_intersect_civ05_idle;
    level.scr_anim[ "generic" ][ "lon_intersect_civ06_idle" ][ 0 ] = %lon_intersect_civ06_idle;
    level.scr_anim[ "generic" ][ "lon_intersect_civ07_idle" ][ 0 ] = %lon_intersect_civ07_idle;
    level.scr_anim[ "generic" ][ "lon_intersect_civ08_idle" ][ 0 ] = %lon_intersect_civ08_idle;
    level.scr_anim[ "generic" ][ "SH_020_marketplace_idleA_civ07" ][ 0 ] = %sh_020_marketplace_idlea_civ07;
    level.scr_anim[ "generic" ][ "SH_020_marketplace_reactF_civ02" ][ 0 ] = %sh_020_marketplace_reactf_civ02;
    level.scr_anim[ "generic" ][ "SH_020_marketplace_reactF_civ03" ][ 0 ] = %sh_020_marketplace_reactf_civ03;
    level.scr_anim[ "generic" ][ "cp_informant_checkin_sit_2_stand" ] = %cp_informant_checkin_sit_2_stand;
    level.scr_anim[ "generic" ][ "cp_informant_checkin_sit_idle" ][ 0 ] = %cp_informant_checkin_sit_idle;
    level.scr_anim[ "generic" ][ "lon_intersect_civ10_standoff" ] = %lon_intersect_civ10_standoff;
    level.scr_anim[ "generic" ][ "lon_intersect_civ12_standoff" ] = %lon_intersect_civ12_standoff;
    level.scr_anim[ "generic" ][ "th_wh_010_infil_approach_police01" ] = %th_wh_010_infil_approach_police01;
    level.scr_anim[ "generic" ][ "th_wh_011_neighborhood_window02_start_civ01" ] = %th_wh_011_neighborhood_window02_start_civ01;
    level.scr_anim[ "generic" ][ "th_wh_011_neighborhood_window01_start_civ01" ] = %th_wh_011_neighborhood_window01_start_civ01;
    level.scr_anim[ "generic" ][ "th_wh_011_neighborhood_window02_start_civ02" ] = %th_wh_011_neighborhood_window02_start_civ02;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_04_FF_k" ][ 0 ] = %ped_idle_casual_rain_group_04_ff_k;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_04_MD_j" ][ 0 ] = %ped_idle_casual_rain_group_04_md_j;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_04_MB_m" ][ 0 ] = %ped_idle_casual_rain_group_04_mb_m;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_05_FG_k" ][ 0 ] = %ped_idle_casual_rain_group_05_fg_k;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_05_MG_m" ][ 0 ] = %ped_idle_casual_rain_group_05_mg_m;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_05_MC_j" ][ 0 ] = %ped_idle_casual_rain_group_05_mc_j;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_03_FD_k" ][ 0 ] = %ped_idle_casual_rain_group_03_fd_k;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_03_MD_j" ][ 0 ] = %ped_idle_casual_rain_group_03_md_j;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_03_MD_m" ][ 0 ] = %ped_idle_casual_rain_group_03_md_m;
    level.scr_anim[ "generic" ][ "ped_idle_casual_rain_group_04_FF_k" ][ 0 ] = %ped_idle_casual_rain_group_04_ff_k;
    level.scr_anim[ "generic" ][ "civ_pnc_run_forward03_fakeactor" ] = %civ_pnc_run_forward03_fakeactor;
    level.scr_anim[ "generic" ][ "emb_def_civ_run_c_civ02" ] = %emb_def_civ_run_c_civ02;
    level.scr_anim[ "generic" ][ "EMB_exfil_005_stacy_hostage_alqatala_enter" ] = %emb_exfil_005_stacy_hostage_alqatala_enter;
    level.scr_anim[ "generic" ][ "EMB_exfil_005_stacy_hostage_alqatala_exitA" ] = %emb_exfil_005_stacy_hostage_alqatala_exita;
    level.scr_anim[ "generic" ][ "EMB_exfil_005_stacy_hostage_alqatala_exitB" ] = %emb_exfil_005_stacy_hostage_alqatala_exitb;
    level.scr_anim[ "generic" ][ "EMB_exfil_005_stacy_hostage_alqatala_idle" ][ 0 ] = %emb_exfil_005_stacy_hostage_alqatala_idle;
    level.scr_anim[ "generic" ][ "EMB_exfil_005_stacy_hostage_stacy_enter" ] = %emb_exfil_005_stacy_hostage_stacy_enter;
    level.scr_anim[ "generic" ][ "EMB_exfil_005_stacy_hostage_stacy_exitA" ] = %emb_exfil_005_stacy_hostage_stacy_exita;
    level.scr_anim[ "generic" ][ "EMB_exfil_005_stacy_hostage_stacy_exitB" ] = %emb_exfil_005_stacy_hostage_stacy_exitb;
    level.scr_anim[ "generic" ][ "EMB_exfil_005_stacy_hostage_stacy_idle" ][ 0 ] = %emb_exfil_005_stacy_hostage_stacy_idle;
    level.scr_anim[ "generic" ][ "cp_civ_tied_hostage_idle_03" ][ 0 ] = %cp_civ_tied_hostage_idle_03;
    level.scr_anim[ "generic" ][ "heist_unroof_finishedE_look_around_guyA" ] = %heist_unroof_finishede_look_around_guya;
    level.scr_anim[ "generic" ][ "grd_stl_patrol_stand_cellphone_start" ] = %emb_exfil_005_stacy_hostage_alqatala_enter;
    level.scr_anim[ "generic" ][ "grd_stl_patrol_stand_cellphone_idle" ][ 0 ] = %grd_stl_patrol_stand_cellphone_idle;
    level.scr_anim[ "generic" ][ "grd_stl_patrol_stand_cellphone_end" ] = %grd_stl_patrol_stand_cellphone_end;
    level.scr_anim[ "generic" ][ "prty_0440_1f_phone_scene_a_idle_civ01" ][ 0 ] = %prty_0440_1f_phone_scene_a_idle_civ01;
    level.scr_anim[ "soap" ][ "reb_stl_idle_stand_smoking" ][ 0 ] = %reb_stl_idle_stand_smoking;
    level.scr_anim[ "soap" ][ "emb_res_015_dejected_idle_civ02" ][ 0 ] = %emb_res_015_dejected_idle_civ02;
    level.scr_anim[ "soap" ][ "emb_res_015_dejected_idle_civ01" ][ 0 ] = %emb_res_015_dejected_idle_civ01;
    level.scr_anim[ "gaz" ][ "emb_res_015_dejected_idle_civ01" ][ 0 ] = %emb_res_015_dejected_idle_civ01;
    level.scr_anim[ "generic" ][ "sdr_com_exposed_stand_long_death_crawl_belly" ] = %sdr_com_exposed_stand_long_death_crawl_belly;
    level.scr_anim[ "generic" ][ "sdr_com_exposed_stand_long_death_crawl_belly_death" ] = %sdr_com_exposed_stand_long_death_crawl_belly_death;
    level.scr_anim[ "generic" ][ "sdr_com_exposed_crouch_long_death_crawl_back" ] = %sdr_com_exposed_crouch_long_death_crawl_back;
    level.scr_anim[ "generic" ][ "sdr_com_exposed_crouch_long_death_crawl_back_death" ] = %sdr_com_exposed_crouch_long_death_crawl_back_death;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_01_enter_enemy01" ] = %jup_surge_0430_chunnel_civ_shield_01_enter_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_01_enter_civ01" ] = %jup_surge_0430_chunnel_civ_shield_01_enter_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_01_idle_enemy01" ][ 0 ] = %jup_surge_0430_chunnel_civ_shield_01_idle_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_01_idle_civ01" ][ 0 ] = %jup_surge_0430_chunnel_civ_shield_01_idle_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_02_enter_enemy01" ] = %jup_surge_0430_chunnel_civ_shield_02_enter_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_02_enter_civ01" ] = %jup_surge_0430_chunnel_civ_shield_02_enter_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_02_idle_enemy01" ][ 0 ] = %jup_surge_0430_chunnel_civ_shield_02_idle_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_02_idle_civ01" ][ 0 ] = %jup_surge_0430_chunnel_civ_shield_02_idle_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_03_enter_enemy01" ] = %jup_surge_0430_chunnel_civ_shield_03_enter_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_03_enter_civ01" ] = %jup_surge_0430_chunnel_civ_shield_03_enter_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_03_idle_enemy01" ][ 0 ] = %jup_surge_0430_chunnel_civ_shield_03_idle_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_03_idle_civ01" ][ 0 ] = %jup_surge_0430_chunnel_civ_shield_03_idle_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_04_enter_enemy01" ] = %jup_surge_0430_chunnel_civ_shield_04_enter_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_04_enter_civ01" ] = %jup_surge_0430_chunnel_civ_shield_04_enter_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_04_idle_enemy01" ][ 0 ] = %jup_surge_0430_chunnel_civ_shield_04_idle_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0430_chunnel_civ_shield_04_idle_civ01" ][ 0 ] = %jup_surge_0430_chunnel_civ_shield_04_idle_civ01;
    level.scr_anim[ "generic" ][ "cap_civ_mtg_texting01" ][ 0 ] = %cap_civ_mtg_texting01;
    level.scr_anim[ "generic" ][ "civ_cap_scn_mtg_couple02_man01_idle" ][ 0 ] = %civ_cap_scn_mtg_couple02_man01_idle;
    level.scr_anim[ "generic" ][ "mtg_0510_canals_civs_bridge_cap01_man01" ][ 0 ] = %mtg_0510_canals_civs_bridge_cap01_man01;
    level.scr_anim[ "generic" ][ "mtg_0530_canals_civs_cafe_cap01_group01_man01" ][ 0 ] = %mtg_0530_canals_civs_cafe_cap01_group01_man01;
    level.scr_anim[ "generic" ][ "civ_cap_rail_group02_male_lean_relax_idle_01" ][ 0 ] = %civ_cap_rail_group02_male_lean_relax_idle_01;
    level.scr_anim[ "generic" ][ "shipcrib_lounge_barstool_idle_01" ][ 0 ] = %shipcrib_lounge_barstool_idle_01;
    level.scr_anim[ "generic" ][ "mtg_0510_canals_civs_bridge_cap01_woman01" ][ 0 ] = %mtg_0510_canals_civs_bridge_cap01_woman01;
    level.scr_anim[ "generic" ][ "mtg_0530_canals_civs_cafe_cap01_group01_woman04" ][ 0 ] = %mtg_0530_canals_civs_cafe_cap01_group01_woman04;
    level.scr_anim[ "generic" ][ "mtg_0520_canals_civs_church_boom03_idleb_man2" ][ 0 ] = %mtg_0520_canals_civs_church_boom03_idleb_man2;
    level.scr_anim[ "generic" ][ "shipcrib_lounge_barstool_idle_04_fem" ][ 0 ] = %shipcrib_lounge_barstool_idle_04_fem;
    level.scr_anim[ "generic" ][ "stp_bar_bartender_idle" ][ 0 ] = %stp_bar_bartender_idle;
    level.scr_anim[ "generic" ][ "shipcrib_lounge_lean_idle_02" ][ 0 ] = %shipcrib_lounge_lean_idle_02;
    level.scr_anim[ "generic" ][ "cap_civ_mtg_ask_direction01_male02_group_loop" ][ 0 ] = %cap_civ_mtg_ask_direction01_male02_group_loop;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_couple01_man01_idle_01" ][ 0 ] = %jup_surge_0100_park_crowd_couple01_man01_idle_01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_couple01_woman01_idle_01" ][ 0 ] = %jup_surge_0100_park_crowd_couple01_woman01_idle_01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_table01_woman01" ][ 0 ] = %jup_surge_0100_park_crowd_table01_woman01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_table01_woman02" ][ 0 ] = %jup_surge_0100_park_crowd_table01_woman02;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_talking_civ01_idle_01" ][ 0 ] = %jup_surge_0100_park_crowd_talking_civ01_idle_01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_talking_civ02_idle_01" ][ 0 ] = %jup_surge_0100_park_crowd_talking_civ02_idle_01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_talking_civ01_idle_02" ][ 0 ] = %jup_surge_0100_park_crowd_talking_civ01_idle_02;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_talking_civ02_idle_02" ][ 0 ] = %jup_surge_0100_park_crowd_talking_civ02_idle_02;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_talking_civ01_idle_03" ][ 0 ] = %jup_surge_0100_park_crowd_talking_civ01_idle_03;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_talking_civ02_idle_03" ][ 0 ] = %jup_surge_0100_park_crowd_talking_civ02_idle_03;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_female_smoking_01_idle" ][ 0 ] = %jup_surge_0100_park_crowd_female_smoking_01_idle;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_smoking_01_idle" ][ 0 ] = %jup_surge_0100_park_crowd_smoking_01_idle;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_smoking_wall_lean_01_idle" ][ 0 ] = %jup_surge_0100_park_crowd_smoking_wall_lean_01_idle;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_smoking_wall_lean_02_idle" ][ 0 ] = %jup_surge_0100_park_crowd_smoking_wall_lean_02_idle;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_child_idle_01" ][ 0 ] = %jup_surge_0100_park_crowd_child_idle_01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_mom_idle_01" ][ 0 ] = %jup_surge_0100_park_crowd_mom_idle_01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_standing_phone_01_idle" ][ 0 ] = %jup_surge_0100_park_crowd_standing_phone_01_idle;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_group01_women01" ][ 0 ] = %jup_surge_0100_park_crowd_group01_women01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_group01_women02" ][ 0 ] = %jup_surge_0100_park_crowd_group01_women02;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_group01_women03" ][ 0 ] = %jup_surge_0100_park_crowd_group01_women03;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_group01_women04" ][ 0 ] = %jup_surge_0100_park_crowd_group01_women04;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_homeless_sitting_civ" ][ 0 ] = %jup_surge_0100_park_crowd_homeless_sitting_civ;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_railing_idle01" ][ 0 ] = %jup_surge_0100_park_crowd_railing_idle01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_railing_female_idle02" ][ 0 ] = %jup_surge_0100_park_crowd_railing_female_idle02;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_sitting_texting_phone_01_idle" ][ 0 ] = %jup_surge_0100_park_crowd_sitting_texting_phone_01_idle;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_sitting_bar_female_01" ][ 0 ] = %jup_surge_0100_park_crowd_sitting_bar_female_01;
    level.scr_anim[ "generic" ][ "ped_fountain_sit_01" ][ 0 ] = %ped_fountain_sit_01;
    level.scr_anim[ "generic" ][ "ped_fountain_sit_04" ][ 0 ] = %ped_fountain_sit_04;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_sitting_ground_01" ][ 0 ] = %jup_surge_0100_park_crowd_sitting_ground_01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_sitting_ground_02" ][ 0 ] = %jup_surge_0100_park_crowd_sitting_ground_02;
    level.scr_anim[ "generic" ][ "mtg_0520_canals_civs_church_dance_idleB_child" ][ 0 ] = %mtg_0520_canals_civs_church_dance_idleb_child;
    level.scr_anim[ "generic" ][ "HTF_POP_030_phone_kid_idle_child01" ][ 0 ] = %htf_pop_030_phone_kid_idle_child01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_sitting_ground_03" ][ 0 ] = %jup_surge_0100_park_crowd_sitting_ground_03;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_railing_carousel_idle01" ][ 0 ] = %jup_surge_0100_park_crowd_railing_carousel_idle01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_idle_civ02" ][ 0 ] = %jup_surge_0100_park_crowd_idle_civ02;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_leaning_bar_civ01" ][ 0 ] = %jup_surge_0100_park_crowd_leaning_bar_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_sitting_ground_04" ][ 0 ] = %jup_surge_0100_park_crowd_sitting_ground_04;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_sitting_feet_up_civ01" ][ 0 ] = %jup_surge_0100_park_crowd_sitting_feet_up_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_sitting_bar_civ01" ][ 0 ] = %jup_surge_0100_park_crowd_sitting_bar_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_sitting_bar_civ02" ][ 0 ] = %jup_surge_0100_park_crowd_sitting_bar_civ02;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_wall_lean_civ01" ][ 0 ] = %jup_surge_0100_park_crowd_wall_lean_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_bartender01" ][ 0 ] = %jup_surge_0100_park_crowd_bartender01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_phone_leaning_civ01" ][ 0 ] = %jup_surge_0100_park_crowd_phone_leaning_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_flag_holding_civ_01" ][ 0 ] = %jup_surge_0100_park_crowd_flag_holding_civ_01;
    level.scr_anim[ "generic" ][ "jup_surge_0100_park_crowd_picture_taking_civ" ][ 0 ] = %jup_surge_0100_park_crowd_picture_taking_civ;
    level.scr_anim[ "generic" ][ "jup_surge_0245_alley_intro_aq01" ] = %jup_surge_0245_alley_intro_aq01;
    level.scr_anim[ "generic" ][ "jup_surge_0245_alley_intro_aq03" ] = %jup_surge_0245_alley_intro_aq03;
    level.scr_anim[ "generic" ][ "jup_surge_0245_alley_intro_aq04" ] = %jup_surge_0245_alley_intro_aq04;
    level.scr_anim[ "generic" ][ "jup_surge_0245_alley_shootout_aq01" ] = %jup_surge_0245_alley_shootout_aq01;
    level.scr_anim[ "generic" ][ "jup_surge_0245_alley_shootout_aq03" ] = %jup_surge_0245_alley_shootout_aq03;
    level.scr_anim[ "generic" ][ "jup_surge_0245_alley_shootout_aq04" ] = %jup_surge_0245_alley_shootout_aq04;
    level.scr_anim[ "soap" ][ "jup_surge_0245_alley_shootout_price" ] = %jup_surge_0245_alley_shootout_price;
    level.scr_anim[ "soap" ][ "jup_surge_0245_alley_intro_price" ] = %jup_surge_0245_alley_intro_price;
    level.scr_anim[ "soap" ][ "jup_surge_0100_park_crowd_sitting_texting_phone_01_idle" ][ 0 ] = %jup_surge_0100_park_crowd_sitting_texting_phone_01_idle;
    level.scr_anim[ "soap" ][ "jup_surge_0227_street_konni_check_idle_block_price" ][ 0 ] = %jup_surge_0227_street_konni_check_idle_block_price;
    level.scr_anim[ "generic" ][ "jup_surge_0227_street_konni_check_idle_enemy01" ][ 0 ] = %jup_surge_0227_street_konni_check_idle_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0227_street_konni_check_idle_atk_enemy01" ][ 0 ] = %jup_surge_0227_street_konni_check_idle_atk_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0227_street_konni_check_idle_end_enemy01" ] = %jup_surge_0227_street_konni_check_idle_end_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0227_street_konni_check_death_enemy01" ] = %jup_surge_0227_street_konni_check_death_enemy01;
    level.scr_goaltime[ "generic" ][ "jup_surge_0227_street_konni_check_idle_end_enemy01" ] = 0;
    level.scr_goaltime[ "generic" ][ "jup_surge_0227_street_konni_check_death_enemy01" ] = 0;
    level.scr_anim[ "generic" ][ "jup_surge_0227_street_konni_check_idle_block_price" ][ 0 ] = %jup_surge_0227_street_konni_check_idle_block_price;
    level.scr_anim[ "generic" ][ "jup_surge_0227_street_konni_check_idle_price" ][ 0 ] = %jup_surge_0227_street_konni_check_idle_price;
    level.scr_anim[ "generic" ][ "jup_surge_0227_street_konni_check_nag_price" ] = %jup_surge_0227_street_konni_check_nag_price;
    level.scr_anim[ "generic" ][ "jup_surge_0490_chunnel_dead_civ01" ][ 0 ] = %jup_surge_0490_chunnel_dead_civ01;
    level.scr_anim[ "generic" ][ "jup_surge_0227_street_konni_check_whiskey_pose" ][ 0 ] = %jup_surge_0227_street_konni_check_whiskey_pose;
    level.scr_anim[ "generic" ][ "jup_surge_0120_park_dead_drop_idle_enemy02" ][ 0 ] = %jup_surge_0120_park_dead_drop_idle_enemy02;
    level.scr_anim[ "generic" ][ "jup_surge_park_target_phone_call_enter" ] = %jup_surge_park_target_phone_call_enter;
    level.scr_anim[ "generic" ][ "jup_surge_park_target_phone_call_scene" ][ 0 ] = %jup_surge_park_target_phone_call_scene;
    level.scr_anim[ "generic" ][ "jup_surge_park_target_phone_call_end" ] = %jup_surge_park_target_phone_call_end;
    level.scr_anim[ "generic" ][ "gnt_com_exposed_crouch_retreat_run_exit02_6" ] = %gnt_com_exposed_crouch_retreat_run_exit02_6;
    level.scr_anim[ "generic" ][ "sdr_com_exposed_retreat_run_exit01_3" ] = %sdr_com_exposed_retreat_run_exit01_3;
    level.scr_anim[ "generic" ][ "corner_standr_blindfire_v1" ] = %corner_standr_blindfire_v1;
    level.scr_anim[ "generic" ][ "sdr_com_exposed_lmg_run_arrival_r_6" ] = %sdr_com_exposed_lmg_run_arrival_r_6;
    level.scr_anim[ "generic" ][ "run_reaction_180" ] = %run_reaction_180;
    level.scr_anim[ "generic" ][ "jup_interaction_alert_doorcode_loop_01" ] = %jup_interaction_alert_doorcode_loop_01;
    level.scr_anim[ "generic" ][ "jup_interaction_alert_doorcode_end" ] = %jup_interaction_alert_doorcode_end;
    level.scr_anim[ "generic" ][ "corner_standl_blindfire_v2" ] = %corner_standl_blindfire_v2;
    level.scr_anim[ "generic" ][ "sdr_com_exp_stand_death01_torso_med_4" ] = %sdr_com_exp_stand_death01_torso_med_4;
    level.scr_anim[ "soap" ][ "jup_surge_1000_igc_outro_scene_soap" ] = %jup_surge_1000_igc_outro_scene_soap;
    level.scr_anim[ "corpse" ][ "deadbody_01" ][ 0 ] = %deadbody_01;
    level.scr_anim[ "corpse" ][ "deadbody_02" ][ 0 ] = %deadbody_02;
    level.scr_anim[ "corpse" ][ "deadbody_03" ][ 0 ] = %deadbody_03;
    level.scr_anim[ "generic" ][ "sdr_com_strafe_jog_start_2" ] = %sdr_com_strafe_jog_start_2;
    level.scr_anim[ "generic" ][ "sdr_com_strafe_jog_2" ][ 0 ] = %sdr_com_strafe_jog_2;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostages_idle01_civ01" ][ 0 ] = %jup_surge_0600_chunnel_hostages_idle01_civ01;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostages_idle01_civ02" ][ 0 ] = %jup_surge_0600_chunnel_hostages_idle01_civ02;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostages_bdie_civ01" ] = %jup_surge_0600_chunnel_hostages_bdie_civ01;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostages_bdie_civ02" ] = %jup_surge_0600_chunnel_hostages_bdie_civ02;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostage_civ_dies_civ01" ] = %jup_surge_0600_chunnel_hostage_civ_dies_civ01;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostage_civ_dies_civ02" ] = %jup_surge_0600_chunnel_hostage_civ_dies_civ02;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostages_blive_civ01" ] = %jup_surge_0600_chunnel_hostages_blive_civ01;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostages_blive_civ02" ] = %jup_surge_0600_chunnel_hostages_blive_civ02;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostage_enemy_dies_civ01" ] = %jup_surge_0600_chunnel_hostage_enemy_dies_civ01;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostage_enemy_dies_civ02" ] = %jup_surge_0600_chunnel_hostage_enemy_dies_civ02;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostage_react_civ01" ] = %jup_surge_0600_chunnel_hostage_react_civ01;
    level.scr_anim[ "hostage" ][ "jup_surge_0600_chunnel_hostage_react_civ02" ] = %jup_surge_0600_chunnel_hostage_react_civ02;
    level.scr_anim[ "hostage_taker" ][ "jup_surge_0600_chunnel_hostages_idle01_enemy01" ][ 0 ] = %jup_surge_0600_chunnel_hostages_idle01_enemy01;
    level.scr_anim[ "hostage_taker" ][ "jup_surge_0600_chunnel_hostages_bdie_enemy01" ] = %jup_surge_0600_chunnel_hostages_bdie_enemy01;
    level.scr_anim[ "hostage_taker" ][ "jup_surge_0600_chunnel_hostage_civ_dies_enemy01" ] = %jup_surge_0600_chunnel_hostage_civ_dies_enemy01;
    level.scr_anim[ "hostage_taker" ][ "jup_surge_0600_chunnel_hostages_blive_enemy01" ] = %jup_surge_0600_chunnel_hostages_blive_enemy01;
    level.scr_anim[ "hostage_taker" ][ "jup_surge_0600_chunnel_hostage_enemy_dies_enemy01" ] = %jup_surge_0600_chunnel_hostage_enemy_dies_enemy01;
    level.scr_anim[ "hostage_taker" ][ "jup_surge_0600_chunnel_hostage_react_enemy01" ] = %jup_surge_0600_chunnel_hostage_react_enemy01;
    level.scr_anim[ "generic" ][ "jup_interaction_patrol_tablet_inventory_loop_01" ][ 0 ] = %jup_interaction_patrol_tablet_inventory_loop_01;
    level.scr_anim[ "generic" ][ "jup_surge_0900_defuse_fight_enemy01" ] = %jup_surge_0900_defuse_fight_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0900_defuse_fight_enemy02" ] = %jup_surge_0900_defuse_fight_enemy02;
    level.scr_anim[ "generic" ][ "jup_surge_0900_defuse_fight_enemy03" ] = %jup_surge_0900_defuse_fight_enemy03;
    level.scr_anim[ "generic" ][ "jup_surge_0900_defuse_fight_enemy04" ] = %jup_surge_0900_defuse_fight_enemy04;
    level.scr_anim[ "generic" ][ "jup_surge_0900_defuse_fight_dead_enemy01" ] = %jup_surge_0900_defuse_fight_dead_enemy01;
    level.scr_anim[ "generic" ][ "jup_surge_0900_defuse_fight_dead_enemy02" ] = %jup_surge_0900_defuse_fight_dead_enemy02;
    level.scr_anim[ "generic" ][ "jup_surge_0900_defuse_fight_dead_enemy03" ] = %jup_surge_0900_defuse_fight_dead_enemy03;
    level.scr_anim[ "generic" ][ "jup_surge_0900_defuse_fight_dead_enemy04" ] = %jup_surge_0900_defuse_fight_dead_enemy04;
    level.scr_anim[ "generic" ][ "sdr_com_exp_crouch_death01_head_med_6" ] = %sdr_com_exp_crouch_death01_head_med_6;
    level.scr_anim[ "generic" ][ "sdr_com_exp_stand_death01_gut_med_4" ] = %sdr_com_exp_stand_death01_gut_med_4;
    level.scr_anim[ "generic" ][ "jup_interaction_patrol_device_low_right_loop" ][ 0 ] = %jup_interaction_patrol_device_low_right_loop;
    level.scr_anim[ "generic" ][ "jup_interaction_patrol_device_low_right_death_6" ] = %jup_interaction_patrol_device_low_right_death_6;
    level.scr_anim[ "generic" ][ "jup_interaction_patrol_device_low_right_react_2" ] = %jup_interaction_patrol_device_low_right_react_2;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_hostilesinfront" ] = %dx_sp_surg_hcqc_gazz_hostilesinfront_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_mandown" ] = %dx_sp_surg_hcqc_gazz_mandown_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_takingfirefromtheupp" ] = %dx_sp_surg_hcqc_gazz_takingfirefromtheupp_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_engaging" ] = %dx_sp_surg_hcqc_soap_engaging_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_iseeem" ] = %dx_sp_surg_hcqc_soap_iseeem_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_rpgdown" ] = %dx_sp_surg_hcqc_soap_rpgdown_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_onyourgosir" ] = %dx_sp_surg_covr_soap_onyourgosir_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_settobreachcallitcap" ] = %dx_sp_surg_covr_soap_settobreachcallitcap_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_waitingonyoucaptain" ] = %dx_sp_surg_covr_soap_waitingonyoucaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_makarovcouldbeherele" ] = %dx_sp_surg_covr_soap_makarovcouldbeherele_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_contact" ] = %dx_sp_surg_covr_soap_contact_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_aye" ] = %dx_sp_surg_covr_soap_aye_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_youheardhimmove" ] = %dx_sp_surg_covr_soap_youheardhimmove_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_needyourguninthefigh" ] = %dx_sp_surg_covr_soap_needyourguninthefigh_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_watchforarmoredtarge" ] = %dx_sp_surg_covr_soap_watchforarmoredtarge_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_theyretakingcoverint" ] = %dx_sp_surg_covr_soap_theyretakingcoverint_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_usepassingtrainsforc" ] = %dx_sp_surg_covr_soap_usepassingtrainsforc_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_theyremovingclose" ] = %dx_sp_surg_covr_soap_theyremovingclose_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_watchthescaffolding" ] = %dx_sp_surg_covr_soap_watchthescaffolding_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_stayoffthetracks" ] = %dx_sp_surg_covr_soap_stayoffthetracks_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_seriousfuckinnumbers" ] = %dx_sp_surg_covr_soap_seriousfuckinnumbers_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_morekonniupaheadcapt" ] = %dx_sp_surg_covr_soap_morekonniupaheadcapt_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_moveforwardletsstayt" ] = %dx_sp_surg_covr_soap_moveforwardletsstayt_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_enemiesinfrontletspr" ] = %dx_sp_surg_covr_soap_enemiesinfrontletspr_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_theyrethinninout" ] = %dx_sp_surg_covr_soap_theyrethinninout_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_gotmorekonniinourpat" ] = %dx_sp_surg_covr_soap_gotmorekonniinourpat_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_itsadistractionkonni" ] = %dx_sp_surg_covr_soap_itsadistractionkonni_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_hesgottabeclose" ] = %dx_sp_surg_covr_soap_hesgottabeclose_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_werenotfarfrommakaro" ] = %dx_sp_surg_covr_soap_werenotfarfrommakaro_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_watchthatjugg" ] = %dx_sp_surg_covr_soap_watchthatjugg_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_slotthatbigbastard" ] = %dx_sp_surg_covr_soap_slotthatbigbastard_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_burnhisdowncaptain" ] = %dx_sp_surg_covr_soap_burnhisdowncaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_weneedtofinishhim" ] = %dx_sp_surg_covr_soap_weneedtofinishhim_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_biggertheyare" ] = %dx_sp_surg_covr_soap_biggertheyare_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_almosttherecaptain" ] = %dx_sp_surg_covr_soap_almosttherecaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_onlyafewleft" ] = %dx_sp_surg_covr_soap_onlyafewleft_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_timetoendthis" ] = %dx_sp_surg_covr_soap_timetoendthis_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_justalittlefurtherca" ] = %dx_sp_surg_covr_soap_justalittlefurtherca_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_hesnotgettinoutalive" ] = %dx_sp_surg_covr_soap_hesnotgettinoutalive_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_comeoncaptainwererun" ] = %dx_sp_surg_covr_soap_comeoncaptainwererun_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_whateverhesgonnadodo" ] = %dx_sp_surg_covr_soap_whateverhesgonnadodo_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_wecantletmakarovesca" ] = %dx_sp_surg_covr_soap_wecantletmakarovesca_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_covr_soap_rogerthatltnosurrend" ] = %dx_sp_surg_covr_soap_rogerthatltnosurrend_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_onyousir" ] = %dx_sp_surg_chin_soap_onyousir_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_letsmoveincaptain" ] = %dx_sp_surg_chin_soap_letsmoveincaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_readytomovesir" ] = %dx_sp_surg_chin_soap_readytomovesir_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_needtogetgoing" ] = %dx_sp_surg_chin_soap_needtogetgoing_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_overherecaptain" ] = %dx_sp_surg_chin_soap_overherecaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_needyouwithme" ] = %dx_sp_surg_chin_soap_needyouwithme_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_needyourgunonthis" ] = %dx_sp_surg_chin_soap_needyourgunonthis_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_whatsmakarovsgame" ] = %dx_sp_surg_chin_soap_whatsmakarovsgame_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_thehell" ] = %dx_sp_surg_chin_soap_thehell_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_steaminjesus" ] = %dx_sp_surg_chin_soap_steaminjesus_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_goodathelpingamadbas" ] = %dx_sp_surg_chin_soap_goodathelpingamadbas_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_thiswaycaptain" ] = %dx_sp_surg_chin_soap_thiswaycaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_crossoversthisway" ] = %dx_sp_surg_chin_soap_crossoversthisway_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_needtofollowthetrack" ] = %dx_sp_surg_chin_soap_needtofollowthetrack_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_thisdirectionsir" ] = %dx_sp_surg_chin_soap_thisdirectionsir_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_makarovwontbeatthecr" ] = %dx_sp_surg_chin_soap_makarovwontbeatthecr_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_letshooftothecrossov" ] = %dx_sp_surg_chin_soap_letshooftothecrossov_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_sirweneedtokeepmovin" ] = %dx_sp_surg_chin_soap_sirweneedtokeepmovin_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_weneedtopushtomakaro" ] = %dx_sp_surg_chin_soap_weneedtopushtomakaro_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_crossoverisupaheadca" ] = %dx_sp_surg_chin_soap_crossoverisupaheadca_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_theydontseeus" ] = %dx_sp_surg_chin_soap_theydontseeus_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_enemiesaheadshouldta" ] = %dx_sp_surg_chin_soap_enemiesaheadshouldta_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_letsambushkonnibefor" ] = %dx_sp_surg_chin_soap_letsambushkonnibefor_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_hostilesareunawarele" ] = %dx_sp_surg_chin_soap_hostilesareunawarele_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_anothertraincomin" ] = %dx_sp_surg_chin_soap_anothertraincomin_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_incomingtraingetofft" ] = %dx_sp_surg_chin_soap_incomingtraingetofft_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_trainincomingmovesir" ] = %dx_sp_surg_chin_soap_trainincomingmovesir_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_theyreassemblingatur" ] = %dx_sp_surg_chin_soap_theyreassemblingatur_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_spottedus" ] = %dx_sp_surg_chin_soap_spottedus_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_traindidthejobforus" ] = %dx_sp_surg_chin_soap_traindidthejobforus_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_clear" ] = %dx_sp_surg_chin_soap_clear_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_ventilationwaysoverh" ] = %dx_sp_surg_chin_soap_ventilationwaysoverh_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_weretakintheventilat" ] = %dx_sp_surg_chin_soap_weretakintheventilat_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_ifwecanusethispassag" ] = %dx_sp_surg_chin_soap_ifwecanusethispassag_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_train" ] = %dx_sp_surg_chin_soap_train_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_incomingtrain" ] = %dx_sp_surg_chin_soap_incomingtrain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_getoffthetracks" ] = %dx_sp_surg_chin_soap_getoffthetracks_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_watchforthetrain" ] = %dx_sp_surg_chin_soap_watchforthetrain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_mindthetrain" ] = %dx_sp_surg_chin_soap_mindthetrain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_train_01" ] = %dx_sp_surg_chin_soap_train_01_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_thiswaycaptainidstay" ] = %dx_sp_surg_chin_soap_thiswaycaptainidstay_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_ventsareoverherecapt" ] = %dx_sp_surg_chin_soap_ventsareoverherecapt_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_setattheventsonyousi" ] = %dx_sp_surg_chin_soap_setattheventsonyousi_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_onyoursix" ] = %dx_sp_surg_chin_soap_onyoursix_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_goforsoap" ] = %dx_sp_surg_chin_soap_goforsoap_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_andifyounabhimfirst" ] = %dx_sp_surg_chin_soap_andifyounabhimfirst_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_hearthatcaptain" ] = %dx_sp_surg_chin_soap_hearthatcaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_wecanstaylowanduseth" ] = %dx_sp_surg_chin_soap_wecanstaylowanduseth_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_gotkonniahead" ] = %dx_sp_surg_chin_soap_gotkonniahead_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_theysawus" ] = %dx_sp_surg_chin_soap_theysawus_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_allclearletspressups" ] = %dx_sp_surg_chin_soap_allclearletspressups_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_needtodisableitonyou" ] = %dx_sp_surg_chin_soap_needtodisableitonyou_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_activeturretahead" ] = %dx_sp_surg_chin_soap_activeturretahead_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_findcover" ] = %dx_sp_surg_chin_soap_findcover_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_turretsonyou" ] = %dx_sp_surg_chin_soap_turretsonyou_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_takecovercaptain" ] = %dx_sp_surg_chin_soap_takecovercaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_needtosecurethehosta" ] = %dx_sp_surg_chin_soap_needtosecurethehosta_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_needtomoveinandsecur" ] = %dx_sp_surg_chin_soap_needtomoveinandsecur_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_thehostagesneedhelpc" ] = %dx_sp_surg_chin_soap_thehostagesneedhelpc_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_nofuckinregardforhum" ] = %dx_sp_surg_chin_soap_nofuckinregardforhum_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_thisis71wereatthecro" ] = %dx_sp_surg_chin_soap_thisis71wereatthecro_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_chin_soap_ihopeheissir" ] = %dx_sp_surg_chin_soap_ihopeheissir_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_needtodisablethattur" ] = %dx_sp_surg_hcqc_soap_needtodisablethattur_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_needtodisabletheturr" ] = %dx_sp_surg_hcqc_soap_needtodisabletheturr_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_copythat" ] = %dx_sp_surg_hcqc_soap_copythat_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_weneedtoclearthisflo" ] = %dx_sp_surg_hcqc_soap_weneedtoclearthisflo_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_letspushforwardkillt" ] = %dx_sp_surg_hcqc_soap_letspushforwardkillt_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_rog" ] = %dx_sp_surg_hcqc_soap_rog_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_konnishootersinthesh" ] = %dx_sp_surg_hcqc_soap_konnishootersinthesh_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_needtodisabletheturr_01" ] = %dx_sp_surg_hcqc_soap_needtodisabletheturr_01_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_cantmoveuntiltheturr" ] = %dx_sp_surg_hcqc_soap_cantmoveuntiltheturr_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_turretsblockingourad" ] = %dx_sp_surg_hcqc_soap_turretsblockingourad_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_nicejobcaptainweremo" ] = %dx_sp_surg_hcqc_soap_nicejobcaptainweremo_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_turretdownedmovingup" ] = %dx_sp_surg_hcqc_soap_turretdownedmovingup_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_turretsdestroyed" ] = %dx_sp_surg_hcqc_soap_turretsdestroyed_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_theyrefallingback" ] = %dx_sp_surg_hcqc_soap_theyrefallingback_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_gotmorekonniinthenex" ] = %dx_sp_surg_hcqc_soap_gotmorekonniinthenex_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_gotthemontherunneedt" ] = %dx_sp_surg_hcqc_soap_gotthemontherunneedt_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_needtomoveupcap" ] = %dx_sp_surg_hcqc_soap_needtomoveupcap_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_whoandwhatwerelookin" ] = %dx_sp_surg_hcqc_soap_whoandwhatwerelookin_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_rpg" ] = %dx_sp_surg_hcqc_soap_rpg_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_rpgonthesecondfloorl" ] = %dx_sp_surg_hcqc_soap_rpgonthesecondfloorl_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_mandown" ] = %dx_sp_surg_hcqc_soap_mandown_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_turretspinninguscapt" ] = %dx_sp_surg_hcqc_soap_turretspinninguscapt_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_popsmokecaptain" ] = %dx_sp_surg_hcqc_soap_popsmokecaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_smokellhideusletsmov" ] = %dx_sp_surg_hcqc_soap_smokellhideusletsmov_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_smokesoutgo" ] = %dx_sp_surg_hcqc_soap_smokesoutgo_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_turretsdown" ] = %dx_sp_surg_hcqc_soap_turretsdown_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_konnisretreatedupsta" ] = %dx_sp_surg_hcqc_soap_konnisretreatedupsta_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_enemyholdingposition" ] = %dx_sp_surg_hcqc_soap_enemyholdingposition_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hcqc_soap_letsgetupthereandgiv" ] = %dx_sp_surg_hcqc_soap_letsgetupthereandgiv_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hitl_soap_fornow" ] = %dx_sp_surg_hitl_soap_fornow_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hitl_soap_copyonyoucaptain" ] = %dx_sp_surg_hitl_soap_copyonyoucaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hitl_soap_checkleadthewaysir" ] = %dx_sp_surg_hitl_soap_checkleadthewaysir_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hitl_soap_readywhenyouarecapta" ] = %dx_sp_surg_hitl_soap_readywhenyouarecapta_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hitl_soap_ayesecondfloorsnotbe" ] = %dx_sp_surg_hitl_soap_ayesecondfloorsnotbe_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hitl_soap_captainsecondfloorof" ] = %dx_sp_surg_hitl_soap_captainsecondfloorof_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hitl_soap_gotanotherroomherebr" ] = %dx_sp_surg_hitl_soap_gotanotherroomherebr_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hitl_soap_wereclear" ] = %dx_sp_surg_hitl_soap_wereclear_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hitl_soap_needtofindthatflashd" ] = %dx_sp_surg_hitl_soap_needtofindthatflashd_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hitl_soap_shouldcheckthelaptop" ] = %dx_sp_surg_hitl_soap_shouldcheckthelaptop_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hitl_soap_theresgottabeintelon" ] = %dx_sp_surg_hitl_soap_theresgottabeintelon_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hint_soap_movingonyoucaptain" ] = %dx_sp_surg_hint_soap_movingonyoucaptain_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hint_soap_letsgetdownstairs" ] = %dx_sp_surg_hint_soap_letsgetdownstairs_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hint_soap_konnisonthelowerleve" ] = %dx_sp_surg_hint_soap_konnisonthelowerleve_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_hint_soap_letsmovedownstairsan" ] = %dx_sp_surg_hint_soap_letsmovedownstairsan_face;
    level.scr_face[ "soap" ][ "dx_sp_surg_stun_soap_71holdingforbreach" ] = %dx_sp_surg_stun_soap_71holdingforbreach_face;
    level.scr_face[ "ghost" ][ "dx_sp_surg_chin_ghos_weregoodherepricerig" ] = %dx_sp_surg_chin_ghos_weregoodherepricerig_face;
    level.scr_face[ "ghost" ][ "dx_sp_surg_chin_ghos_youretakingtherightt" ] = %dx_sp_surg_chin_ghos_youretakingtherightt_face;
    level.scr_face[ "ghost" ][ "dx_sp_surg_chin_ghos_gotlefttunnelcovered" ] = %dx_sp_surg_chin_ghos_gotlefttunnelcovered_face;
    level.scr_face[ "ghost" ][ "dx_sp_surg_chin_ghos_soapswaitinonyoupric" ] = %dx_sp_surg_chin_ghos_soapswaitinonyoupric_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_covr_gazz_noshortageofhostiles" ] = %dx_sp_surg_covr_gazz_noshortageofhostiles_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_covr_gazz_captainkonnispressin" ] = %dx_sp_surg_covr_gazz_captainkonnispressin_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_chin_gazz_weresetherecap" ] = %dx_sp_surg_chin_gazz_weresetherecap_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_chin_gazz_goodheresirsoapshold" ] = %dx_sp_surg_chin_gazz_goodheresirsoapshold_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_chin_gazz_wegotleftsidesiryour" ] = %dx_sp_surg_chin_gazz_wegotleftsidesiryour_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_chin_gazz_regroupwithsoapandle" ] = %dx_sp_surg_chin_gazz_regroupwithsoapandle_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_chin_gazz_youreontherightsidet" ] = %dx_sp_surg_chin_gazz_youreontherightsidet_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_rogmovingrightside" ] = %dx_sp_surg_hcqc_gazz_rogmovingrightside_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_wecanflankthroughthe" ] = %dx_sp_surg_hcqc_gazz_wecanflankthroughthe_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_itsontheleft" ] = %dx_sp_surg_hcqc_gazz_itsontheleft_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_rogerthat" ] = %dx_sp_surg_hcqc_gazz_rogerthat_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_konnisnearihearem" ] = %dx_sp_surg_hcqc_gazz_konnisnearihearem_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_konnisinsideihearem" ] = %dx_sp_surg_hcqc_gazz_konnisinsideihearem_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_russianthatskonnithe" ] = %dx_sp_surg_hcqc_gazz_russianthatskonnithe_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_captainwegotmoreenem" ] = %dx_sp_surg_hcqc_gazz_captainwegotmoreenem_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_letspushupandclearth" ] = %dx_sp_surg_hcqc_gazz_letspushupandclearth_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_captainwegotmoreenem_01" ] = %dx_sp_surg_hcqc_gazz_captainwegotmoreenem_01_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_captainwestillneedto" ] = %dx_sp_surg_hcqc_gazz_captainwestillneedto_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_rogmovingtothelavato" ] = %dx_sp_surg_hcqc_gazz_rogmovingtothelavato_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_loosclearmovingup" ] = %dx_sp_surg_hcqc_gazz_loosclearmovingup_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_morekonnidescendingt" ] = %dx_sp_surg_hcqc_gazz_morekonnidescendingt_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_theyrepushingembackl" ] = %dx_sp_surg_hcqc_gazz_theyrepushingembackl_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_konnistakingdefensiv" ] = %dx_sp_surg_hcqc_gazz_konnistakingdefensiv_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_letskeeppushingwithh" ] = %dx_sp_surg_hcqc_gazz_letskeeppushingwithh_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_rpgreloadingtakehimo" ] = %dx_sp_surg_hcqc_gazz_rpgreloadingtakehimo_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_anotherenemyturretba" ] = %dx_sp_surg_hcqc_gazz_anotherenemyturretba_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_turretsholdingusback" ] = %dx_sp_surg_hcqc_gazz_turretsholdingusback_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_needtogainsomeground" ] = %dx_sp_surg_hcqc_gazz_needtogainsomeground_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_capifyougotsmokepopi" ] = %dx_sp_surg_hcqc_gazz_capifyougotsmokepopi_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_goodscreenpushup" ] = %dx_sp_surg_hcqc_gazz_goodscreenpushup_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_usethesmokeletsgo" ] = %dx_sp_surg_hcqc_gazz_usethesmokeletsgo_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hcqc_gazz_hostilesduginontheup" ] = %dx_sp_surg_hcqc_gazz_hostilesduginontheup_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hitl_gazz_weclear" ] = %dx_sp_surg_hitl_gazz_weclear_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hitl_gazz_mustvebeenguardingso" ] = %dx_sp_surg_hitl_gazz_mustvebeenguardingso_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hitl_gazz_goodcallsoap" ] = %dx_sp_surg_hitl_gazz_goodcallsoap_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hitl_gazz_needtosweepandcleart" ] = %dx_sp_surg_hitl_gazz_needtosweepandcleart_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hitl_gazz_leadusinsix" ] = %dx_sp_surg_hitl_gazz_leadusinsix_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hitl_gazz_hesdown" ] = %dx_sp_surg_hitl_gazz_hesdown_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hitl_gazz_needtofindthatflashd" ] = %dx_sp_surg_hitl_gazz_needtofindthatflashd_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hitl_gazz_flashdrivesgottabear" ] = %dx_sp_surg_hitl_gazz_flashdrivesgottabear_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hitl_gazz_checkthelaptop" ] = %dx_sp_surg_hitl_gazz_checkthelaptop_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hint_gazz_goodbreachcapletsmov" ] = %dx_sp_surg_hint_gazz_goodbreachcapletsmov_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hint_gazz_onyoucap" ] = %dx_sp_surg_hint_gazz_onyoucap_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hint_gazz_letspushdownstairsca" ] = %dx_sp_surg_hint_gazz_letspushdownstairsca_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hint_gazz_downstairscaponyou" ] = %dx_sp_surg_hint_gazz_downstairscaponyou_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_hint_gazz_shouldheaddownsir" ] = %dx_sp_surg_hint_gazz_shouldheaddownsir_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_pstl_gazz_wellneedeyes" ] = %dx_sp_surg_pstl_gazz_wellneedeyes_face;
    level.scr_face[ "gaz" ][ "dx_sp_surg_stun_gazz_6issetonyoucaptain" ] = %dx_sp_surg_stun_gazz_6issetonyoucaptain_face;
}

#using_animtree( "player" );

// Namespace namespace_4ef95c8017583719 / namespace_2d132edcaaf1f5af
// Params 0
// Checksum 0x0, Offset: 0xa1b6
// Size: 0x55
function player_anims()
{
    level.scr_model[ "player_rig" ] = "vm_c_jup_sp_hero_price_london_tactical";
    level.scr_anim[ "player_rig" ][ "surge_ges_distract_smoke_lhand" ] = %jup_surge_ges_distract_smoke_ally01_lhand;
    level.scr_anim[ "player_rig" ][ "surge_ges_distract_smoke_rhand" ] = %jup_surge_ges_distract_smoke_ally01_rhand;
}

#using_animtree( "script_model" );

// Namespace namespace_4ef95c8017583719 / namespace_2d132edcaaf1f5af
// Params 0
// Checksum 0x0, Offset: 0xa213
// Size: 0x33
function init_anim_script_model()
{
    level.scr_animtree[ "camp_garageDoor1" ] = #animtree;
    level.scr_anim[ "camp_garageDoor1" ][ "camp_garageDoorOpen" ] = %icpt_0220_farm_rolling_door_md_open;
}

