const char* poolNames[] {
    "physicslibrary", // 0
    "physicssfxeventasset", // 1
    "physicsvfxeventasset", // 2
    "physicsasset", // 3
    "physicsfxpipeline", // 4
    "physicsfxshape", // 5
    "physicsdebugdata", // 6
    "xanim", // 7
    "xmodelsurfs", // 8
    "xmodel", // 9
    "mayhem", // a
    "material", // b
    "computeshader", // c
    "tileshader", // d
    "libshader", // e
    "vertexshader", // f
    "hullshader", // 10
    "domainshader", // 11
    "pixelshader", // 12
    "serializedshader", // 13
    "techset", // 14
    "image", // 15
    "soundglobalvolmod", // 16
    "soundglobalentchannel", // 17
    "soundglobalcontext", // 18
    "soundglobalwhizby", // 19
    "soundglobalbulletcrack", // 1a
    "soundglobalperk", // 1b
    "soundglobalocclusion", // 1c
    "soundglobalsurfaceinfo", // 1d
    "soundglobalcurve", // 1e
    "soundglobaldoppler", // 1f
    "soundglobalshapecone", // 20
    "soundglobalfutz", // 21
    "soundglobalsendeffect", // 22
    "soundglobalnametable", // 23
    "soundglobalfactiontable", // 24
    "soundbank", // 25
    "soundbank_merge", // 26
    "soundbanktransient", // 27
    "col_map", // 28
    "com_map", // 29
    "glass_map", // 2a
    "aipaths", // 2b
    "navmesh", // 2c
    "tacgraph", // 2d
    "airegiongraphs", // 2e
    "map_ents", // 2f
    "map_ents_trzone", // 30
    "fx_map", // 31
    "gfx_map", // 32
    "gfx_map_trzone", // 33
    "iesprofile", // 34
    "lightdef", // 35
    "gradingclut", // 36
    "fogspline", // 37
    "animclass", // 38
    "playeranim", // 39
    "gesture", // 3a
    "localize", // 3b
    "attachment", // 3c
    "weapon", // 3d
    "vfx", // 3e
    "impactfx", // 3f
    "surfacefx", // 40
    "aitype", // 41
    "character", // 42
    "xmodelalias", // 43
    "rawfile", // 44
    "gscobj", // 45
    "gscgdb", // 46
    "stringtable", // 47
    "ddl", // 48
    "tracer", // 49
    "vehicle", // 4a
    "netconststrings", // 4b
    "luafile", // 4c
    "scriptable", // 4d
    "vectorfield", // 4e
    "particlesimanimation", // 4f
    "streaminginfo", // 50
    "laser", // 51
    "gameprops", // 52
    "materialstandard", // 53
    "beam", // 54
    "ttf", // 55
    "suit", // 56
    "suitanimpackage", // 57
    "camera", // 58
    "hudoutline", // 59
    "rumble", // 5a
    "rumblegraph", // 5b
    "animpkg", // 5c
    "sfxpkg", // 5d
    "vfxpkg", // 5e
    "footstepvfx", // 5f
    "behaviortree", // 60
    "behaviorsequencer", // 61
    "sightconfig", // 62
    "sightconfigtemplate", // 63
    "aianimset", // 64
    "aiasm", // 65
    "proceduralbones", // 66
    "dynamicbones", // 67
    "proceduralblendweights", // 68
    "reticle", // 69
    "xanimcurve", // 6a
    "coverselector", // 6b
    "enemyselector", // 6c
    "clientcharacter", // 6d
    "clothasset", // 6e
    "cinematicmotion", // 6f
    "accessory", // 70
    "locdmgtable", // 71
    "bulletpenetration", // 72
    "scriptbundle", // 73
    "blendspace2d", // 74
    "xcam", // 75
    "camo", // 76
    "xcompositemodel", // 77
    "xmodeldetailcollision", // 78
    "streamtreeoverride", // 79
    "keyvaluepairs", // 7a
    "stterrain", // 7b
    "vhmdata", // 7c
    "vtm_surfacemapsdata", // 7d
    "collisiontile", // 7e
    "execution", // 7f
    "carryobject", // 80
    "soundbanklist", // 81
    "weaponaccuracy", // 82
    "decalvolumematerial", // 83
    "decalvolumemask", // 84
    "dynentitylist", // 85
    "fx_map_trzone", // 86
    "volumetricheightmap", // 87
    "dlogschema", // 88
    "edgelist", // 89
    "standaloneumbratome", // 8a
    "xboneset", // 8b
    "ragdollasset", // 8c
    "physicsbonegraph", // 8d
    "curve", // 8e
    "skeletonconstraints", // 8f
    "triggereffect", // 90
    "weapontrigger", // 91
    "volumetriccloud", // 92
    "codcasterdata", // 93
    "watersystem", // 94
    "waterbuoyancy", // 95
    "keybinds", // 96
    "calloutmarkerping", // 97
    "lightstate", // 98
    "radianttelemetry", // 99
    "aimarkup", // 9a
    "aimarkup_generated", // 9b
    "scenario", // 9c
    "ai_interaction", // 9d
    "mapvoxelizedstateformat", // 9e
    "watervis", // 9f
    "gametype", // a0
    "gametypetable", // a1
    "sndmodifier", // a2
    "weaponblueprint", // a3
    "attachmentblueprint", // a4
    "movingplatform", // a5
    "hwconfig", // a6
    "timelapsesky", // a7
    "hwconfiguratorinfo", // a8
    "objectivedata", // a9
    "font", // aa
    "motionmatchingfeatures", // ab
    "motionmatchingset", // ac
    "gametypestatdata", // ad
    "fonticon", // ae
    "calloutmarkerpingwheel", // af
    "hwconfigvar", // b0
    "zivart", // b1
    "movie", // b2
    "mapinfo", // b3
    "maptable", // b4
    "achievement", // b5
    "achievementlist", // b6
    "materialdebugdata", // b7
    "scriptablevariant", // b8
    "leagueplayseasons", // b9
    "settingcontext", // ba
    "ai_eventlist", // bb
    "soundevent", // bc
    "calloutmarkerpingmetadata", // bd
    "project", // be
    "projecttable", // bf
    "gamemode", // c0
    "sndasset", // c1
    "gfxumbratome", // c2
    "audiovisualizer", // c3
    "materialanimationparams", // c4
    "nameplatesettings", // c5
    "reactiveaudioparams", // c6
    "reactivevfxpackage", // c7
    "materialsfxtable", // c8
    "footstepsfxtable", // c9
    "reactivestageset", // ca
    "foliagesfxtable", // cb
    "impactsfxtable", // cc
    "aiimpactvfxtable", // cd
    "typeinfo", // ce
    "handplantsfxtable", // cf
    "sndtable", // d0
    "equipmentsfx", // d1
    "soundsubmix", // d2
    "shock", // d3
    "storagefile", // d4
    "ecsasset", // d5
    "trackerfootstepfx", // d6
    "playerspawnsettings", // d7
    "playerspawninfluencer", // d8
    "soundspeakermap", // d9
    "reverbpreset", // da
    "aishootstyleslist", // db
    "operatorlist", // dc
    "operator", // dd
    "operatorskin", // de
    "dismemberment", // df
    "conversation", // e0
    "xanimnode", // e1
    "sndmodifierset", // e2
    "sndcurve", // e3
    "ttlos", // e4
    "materialtintanimationparams", // e5
    "materialuvanimationparams", // e6
    "materialcamoanimationparams", // e7
    "materialanimation", // e8
    "impactfxtable", // e9
    "impacttypetoimpactfxtable", // ea
    "reactiveoperator", // eb
    "weathervolume", // ec
    "vehicletrick", // ed
    "reactiveaudiopackage", // ee
    "ambientsfxpackage", // ef
    "objectstoreproject", // f0
    "objectstoregamemode", // f1
    "proceduralbonelodsettings", // f2
    "hwconfigvargroup", // f3
    "hwconfigtieredgroup", // f4
    "sndmasterpreset", // f5
    "genericblueprint", // f6
};