// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

asm_register()
{
    if ( !isdefined( anim.asmfuncs ) )
        anim.asmfuncs = [];

    if ( isdefined( anim.asmfuncs["_encstr_AA821B5B7F53A5BF83B1FF57ACFF53B7F1283F7076E738C5C8FBB712F3"] ) )
        return;

    anim.asmfuncs["_encstr_AA821B5B7F53A5BF83B1FF57ACFF53B7F1283F7076E738C5C8FBB712F3"] = [];
    anim.asmfuncs["_encstr_AA821B5B7F53A5BF83B1FF57ACFF53B7F1283F7076E738C5C8FBB712F3"][0] = scripts\asm\soldier\script_funcs::shoot_generic;
    anim.asmfuncs["_encstr_AA821B5B7F53A5BF83B1FF57ACFF53B7F1283F7076E738C5C8FBB712F3"][1] = scripts\asm\shoot\script_funcs::shoot_playidleanimloop;
    anim.asmfuncs["_encstr_AA821B5B7F53A5BF83B1FF57ACFF53B7F1283F7076E738C5C8FBB712F3"][2] = ::autogenfunc_0;
}

autogenfunc_0( var_0, var_1, var_2, var_3 )
{
    return isdefined( self.node ) && self.node.type == "_encstr_A7760B6710A315533959DF17AD";
}
