// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    self.additionalassets = "";
    self.team = "axis";
    self.type = "human";
    self.unittype = "soldier";
    self.subclass = "regular";
    self.accuracy = 0.2;
    self.health = 150;
    self.grenadeweapon = getcompleteweaponname( "frag" );
    self.grenadeammo = 2;
    self.secondaryweapon = scripts\code\ai::create_weapon_in_script( "" );
    self.sidearm = scripts\code\ai::create_weapon_in_script( "iw8_pi_mike1911", "sidearm" );
    self.behaviortreeasset = "enemy_combatant";
    self.asmasset = "soldier";
    self.defaultcoverselector = "cover_default";
    self.enemyselector = "enemyselector_default";

    if ( isai( self ) )
    {
        self setengagementmindist( 512.0, 400.0 );
        self setengagementmaxdist( 1024.0, 1250.0 );
    }

    self.usescriptedweapon = 1;
    self.scriptedweaponclassprimary = "lmg";
    self.weapon = scripts\code\ai::create_weapon_in_script( [ "iw8_lm_pkilo", "iw8_lm_mgolf34" ] );
    var_0 = undefined;
    var_1 = [ "character_al_qatala_urban_lmg_variant" ];

    switch ( scripts\code\character::get_random_character( 1, var_0, var_1 ) )
    {
        case 0:
            character\character_al_qatala_urban_lmg_variant::main();
            break;
    }
}

spawner()
{
    self setspawnerteam( "axis" );
}

precache( var_0 )
{
    character\character_al_qatala_urban_lmg_variant::precache();
    scripts\aitypes\bt_util::init();
    scripts\aitypes\assets::soldier();
    behaviortree\enemy_combatant::registerbehaviortree();
    aiasm\soldier_sp::asm_register();
    precacheitem( "iw8_lm_pkilo" );
    precacheitem( "iw8_lm_mgolf34" );
    precacheitem( "iw8_pi_mike1911" );
    precacheitem( "frag" );
}
