NAME scripts\cp_mp\killstreaks\white_phosphorus.gsc
VERSION 0
CHECKSUM 0x38d646fe
######################################################
####################  DEV BLOCKS  ####################
######################################################
# white_phosphorus::init@53
DEVBLOCK 0x969
# white_phosphorus::wp_finishdeployment@71
DEVBLOCK 0xe12
# white_phosphorus::wp_createplane@a6
DEVBLOCK 0xee4
# white_phosphorus::wp_watchforsmokedisowned@3c
DEVBLOCK 0x10fd
# white_phosphorus::wp_watchforflaredisowned@69
DEVBLOCK 0x1198
# white_phosphorus::wp_deliverpayloads@e2
DEVBLOCK 0x12ac
# white_phosphorus::wp_deliverpayloads@192
DEVBLOCK 0x135c
# white_phosphorus::wp_testpayloads@33
DEVBLOCK 0x1799
# white_phosphorus::wp_fireairburst@64
DEVBLOCK 0x1875
# white_phosphorus::wp_firesmoke@12a
DEVBLOCK 0x1a14
# white_phosphorus::wp_firesmoke@1a3
DEVBLOCK 0x1a8d
# white_phosphorus::wp_firesmoke@343
DEVBLOCK 0x1c2d
# white_phosphorus::wp_fireflaregroup@16f
DEVBLOCK 0x1e07
# white_phosphorus::wp_fireflaregroup@1c0
DEVBLOCK 0x1e58
# white_phosphorus::wp_projwatchimpact@103
DEVBLOCK 0x226f
# white_phosphorus::wp_delayzonedelete@2b
DEVBLOCK 0x2413
# white_phosphorus::wp_removefromactivewplist@23f
DEVBLOCK 0x2cf7
# white_phosphorus::wp_startdisorientplayer@d4
DEVBLOCK 0x3221
# white_phosphorus::wp_startburnplayer@83
DEVBLOCK 0x353a
# white_phosphorus::wp_startblindplayer@56
DEVBLOCK 0x36df
# white_phosphorus::wp_removeplane@a
DEVBLOCK 0x3898
# white_phosphorus::disableloopingcoughaudio@19
DEVBLOCK 0x3ad9
# white_phosphorus::disableloopingcoughaudiosupression@19
DEVBLOCK 0x3e15
