NAME scripts\asm\soldier\patrol_idle.gsc
VERSION 0
CHECKSUM 0xa5afca6
######################################################
####################  DEV BLOCKS  ####################
######################################################
# patrol_idle::patrol_idle_istype@22
DEVBLOCK 0x487
# patrol_idle::patrol_idle_istype@2d
DEVBLOCK 0x492
# patrol_idle::patrol_idle_istype@49
DEVBLOCK 0x4ae
# patrol_idle::patrol_playanim@7d
DEVBLOCK 0x624
# patrol_idle::patrol_playidleloop@9d
DEVBLOCK 0x7e3
# patrol_idle::patrol_playidlereact@f6
DEVBLOCK 0x9b4
# patrol_idle::patrol_playidlesittingloop@9d
DEVBLOCK 0x1063
# patrol_idle::patrol_playidlesittingloop@b9
DEVBLOCK 0x107f
# patrol_idle::patrol_playidlesittingloop@13d
DEVBLOCK 0x1103
# patrol_idle::patrol_playdeathanim_sitting@27
DEVBLOCK 0x13a0
# patrol_idle::patrol_hascustomanim@6f
DEVBLOCK 0x1497
# patrol_idle::patrol_iscustomanimdefaultvalue@6f
DEVBLOCK 0x1559
# patrol_idle::patrol_iscustomanimdefaultvalue@7a
DEVBLOCK 0x1564
# patrol_idle::patrol_chooseanim_custom@35
DEVBLOCK 0x1602
# patrol_idle::patrol_chooseanim_custom@6a
DEVBLOCK 0x1637
# patrol_idle::patrol_chooseanim_custom@75
DEVBLOCK 0x1642
# patrol_idle::patrol_chooseanim_custom@88
DEVBLOCK 0x1655
# patrol_idle::patrol_chooseanim_custom@ba
DEVBLOCK 0x1687
# patrol_idle::patrol_chooseanim_custom@ee
DEVBLOCK 0x16bb
# patrol_idle::patrol_chooseanim_custom@15d
DEVBLOCK 0x172a
# patrol_idle::patrol_idle_custom_init@1a
DEVBLOCK 0x17f6
# patrol_idle::patrol_idle_custom_init@36
DEVBLOCK 0x1812
# patrol_idle::patrol_idle_callcustomcallback@20
DEVBLOCK 0x18de
# patrol_idle::patrol_playidle_custom_terminate@1a
DEVBLOCK 0x1a4a
# patrol_idle::patrol_playidle_custom_terminate@37
DEVBLOCK 0x1a67
